### ISSUE TITLE
Modal - View Submission - Push view

### ISSUE THREAD

**Issue by RicardoCostaPS** [soxtoby/SlackNet#102]
Hi SlackNet team,

I have been using your api to create modals, great work guys, I have got a question regarding pushing new views during a view submission, from slack documentation it should be possible to push a new view into a modal during submission as stated ( https://github.com/slackapi/bolt-js/issues/531 ). I tried to return PushViewResponse class during a Task<ViewSubmissionResponse> Handle(ViewSubmission viewSubmission) method, but my view wasn't visible ( the view didn't change or update ), is there any way to accomplish this task ?

**Comment by soxtoby** [comment]
Hi @RicardoCostaPS, returning a `PushViewResponse` should work just fine. It's possible your view isn't passing Slack's validation though, and unfortunately you don't get any feedback when returning a new view this way.

I'd recommend adding a test button to your base view and in its handler, push your new view with `IViewsApi.Push()` - that way you'll get an error if the view doesn't pass validation. Once the new view is working, you can go back to returning it from the `ViewSubmmission` handler.

Hope that helps.
