### ISSUE TITLE
Header block not showing emoji

### ISSUE THREAD

**Issue by Fraysa** [soxtoby/SlackNet#103]
When trying to send a `HeaderBlock` with emojis surrounded by colons (e.g. `:gear:`), they don't render in Slack.

I tried to manually send a request with Postman to Slack, and it does show, which indicates this is an issue with SlackNet.

Example:
![image](https://user-images.githubusercontent.com/1190747/164976047-84a59e7a-97c1-41b0-ae3e-7adc7d2bfe18.png)

Example of manually sending using Slack's API:
![image](https://user-images.githubusercontent.com/1190747/164976057-12c269b0-5a82-4d50-be5d-0d06870617ce.png)

**Comment by soxtoby** [comment]
Thanks for raising this, @Fraysa. Looks like the default for `PlainText.Emoji` was wrong. I'll have a fix up soon.

**Comment by soxtoby** [comment]
Should be fixed in [v0.10.5](https://github.com/soxtoby/SlackNet/releases/tag/v0.10.5).
