### ISSUE TITLE
Missing Subtype property on MessageEvent

### ISSUE THREAD

**Issue by pkmetski** [soxtoby/SlackNet#104]
Hi, I just updated to 0.10.5 and my app failed to build. I am missing `Subtype` property on `MessageEvent` and it has been deleted. It looks like related to [this](https://github.com/soxtoby/SlackNet/commit/d03ce9e53de6aa77f417b30157ad67d03290f04c#diff-0089bef8584b2d3634b22092656c81a59a51760fa56816acc10bec7d02563c46L11) commit. 
I assume this is not intentional, as it's also not present in the changelog. Can you please advise? Thank you!

**Comment by soxtoby** [comment]
Ah, yep looks like `Subtype` was accidentally removed. Thanks for raising this, @pkmetski. I'll have a fix up shortly.

**Comment by soxtoby** [comment]
Should be fixed in [v0.10.6](https://github.com/soxtoby/SlackNet/releases/tag/v0.10.6).
