### ISSUE TITLE
Team ID optional argument missing from Conversations.List

### ISSUE THREAD

**Issue by jtsai-osa** [soxtoby/SlackNet#105]
The API documentation https://api.slack.com/methods/conversations.list has an optional argument to specify the team_id. This is needed because an org level token can access multiple workspaces. Is it possible to add this to the Conversations.List method?
Thanks!

**Comment by soxtoby** [comment]
Thanks for raising this and providing a PR - I've pushed up your change in [v0.10.7](https://github.com/soxtoby/SlackNet/releases/tag/v0.10.7).
