### ISSUE TITLE
Channels multiselect: Empty initial channels list leads to unexpected behavior

### ISSUE THREAD

**Issue by makeitokay** [soxtoby/SlackNet#114]
I will describe the situation I had.
I have a modal view in which there is an input block - a multiselect of public channels, and `Optional` is false. I didn't pass the `InitialChannels` to my Multiselect, so it was initiated in a class in SlackNET as an empty list. Because of this, unexpected behavior appeared: despite `Optional = false`, the modal view still allows you to click the submit without selecting any channels. At the same time, if you select a channel and remove it, then everything worked fine. As explained to me in Slack support, this is due to the empty `InitialChannels` list. If you remove the initiation of an empty list in the `ChannelMultiSelectMenu` class (or just pass it to null in object initializer), everything works as it should. 
I attach a GIF with demonstrating of the problem when initiating an empty list. The first time I didn't select any channels and was able to click submit, the second time I selected a channel and removed it - and the field suddenly becomes required :)
I don't know if other input blocks have similar behavior, but it came as a surprise to me.
![channels_multiselect_issue](https://user-images.githubusercontent.com/34311075/184533407-34508a13-c9f8-4989-9302-82eaff3b0672.gif)

**Comment by soxtoby** [comment]
Thanks for raising this, @makeitokay.

I've been able to reproduce the problem, and I'll push a fix up in the next few days. In the meantime, you can explicitly set `InitialChannels` to `null` to get the desired behaviour.

**Comment by soxtoby** [comment]
The fix is now available in [v0.10.10](https://github.com/soxtoby/SlackNet/releases/tag/v0.10.10).
