### ISSUE TITLE
BlockActionRequest does not contain state values

### ISSUE THREAD

**Issue by makeitokay** [soxtoby/SlackNet#115]
According to the Slack [documentation](https://api.slack.com/reference/interaction-payloads/block-actions#fields), the payload of action, which originates from message, contains the element "state.values". It's true, for example, that Slack sent me when I pressed the button. There is a value of the StaticSelectMenu, which is in the same message with my button.
```
"state": {
	"values": {
		"XRS": {
			"department-select-action": {
				"type": "static_select",
				"selected_option": {
					"text": {
						"type": "plain_text",
						"text": "marketing",
						"emoji": true
					},
					"value": "marketing"
				}
			}
		}
	}
}
```
The problem is that the BlockActionRequest class does not contain this state. It is only in ViewInfo. That is, using interactivity in messages, the opportunity to look at the values in other actions disappears.
It would be great if such an opportunity would appear.
Thank you for your attention to these issues!

**Comment by soxtoby** [comment]
Fix is now available in [v0.10.11](https://github.com/soxtoby/SlackNet/releases/tag/v0.10.11). I opted to keep `ViewState` as the type name for the state to avoid breaking changes.
