### ISSUE TITLE
Weird delay in first message

### ISSUE THREAD

**Issue by gingertez** [soxtoby/SlackNet#116]
Hi,

I am seeing some strange behaviour on app startup using SlackNet on ASP NET (net 6.0).

The first app mention isn't being handled until after I also do a slash command.

My bot user is called @plantuml and after app startup when I go into Slack and mention the bot I see a log message indicating that my app has received a POST from Slack:

`POST 200 610 B 443ms   Slackbot 1.0 (+https://api.slack.com/robots) https://plantuml-slack-app-v2hn2hgeza-uc.a.run.app/slack/event`

I don't see a log entry indicating that it is being handled by my registered handler nor do I see my own log message that I've put as the first line in the handler.

Then, after I use a slash command (anywhere from a few seconds to a couple of minutes later) I see the SlackNet log message telling me the app_mention is being handled:

`Handling app_mention event with PlantUmlSlackApp.EventHandlers.AppMentionHandler, PlantUmlSlackApp.EventHandlers.GenericEventHandler`
And I see my own log message I've put in as the first line in the handler.

Then I see the slash command handler log message:

`Handling slash command /plantuml with PlantUmlSlackApp.EventHandlers.SlashCommandHandler`

_To reiterate... the app mention handler doesn't get handled until I subsequently perform a slash command_ 

After this all further app mentions work okay, until the ASPNET service recycles itself the next day - it's just the first one after startup which gets delayed until a slash command is used.

My `Program.cs` looks like this:
```
using SlackNet.AspNetCore;
using SlackNet.Events;
using PlantUmlSlackApp.Models;
using PlantUmlSlackApp.EventHandlers;
using PlantUmlSlackApp.Services;
using PlantUmlSlackApp.Data;
using Microsoft.EntityFrameworkCore;

var builder = WebApplication.CreateBuilder(args);

var slackConfig = builder.Configuration.GetSection("Slack").Get<SlackConfiguration>();

// Add services to the container.

builder.Services.AddControllers();

builder.Services.AddSlackNet(c => c
    .RegisterSlashCommandHandler<SlashCommandHandler>("/plantuml")
    .RegisterEventHandler<AppMention, AppMentionHandler>()
    .RegisterEventHandler<GenericEventHandler>()
    );

builder.Services.AddHttpClient("PlantUml", httpClient =>
{
    httpClient.BaseAddress = new Uri(builder.Configuration["PlantUmlRendererUrl"]);
});

builder.Services.AddDbContext<ApplicationDbContext>(
    dbContextOptions =>
    {
        dbContextOptions
            .UseMySql(
                builder.Configuration.GetConnectionString("DefaultConnection"),
                new MySqlServerVersion(new Version(5, 7)),
                options => {
                    options.EnableRetryOnFailure();
                    options.CommandTimeout(10);
                    })
            .EnableSensitiveDataLogging()
            .EnableDetailedErrors();
    });

builder.Services.AddTransient<ISlackChannelPosterService, SlackChannelPosterService>();
builder.Services.AddTransient<ISlackInstallationService, SlackInstallationService>();
builder.Services.AddTransient<IRenderTrackingService, RenderTrackingService >();

var app = builder.Build();

app.UseHttpsRedirection();

app.UseAuthorization();

app.MapControllers();

app.UseSlackNet(c => c.UseSigningSecret(slackConfig.SigningSecret));

app.Run();
```

btw - I'm on the latest version - `0..10.10`

**Comment by soxtoby** [comment]
Hi @gingertez,

Not exactly sure what would cause this, but it _might_ be related to the way SlackNet uses [HttpResponse.OnCompleted](https://docs.microsoft.com/en-us/dotnet/api/Microsoft.AspNetCore.Http.HttpResponse.OnCompleted) to run handlers _after_ the request has completed (Slack expects a quick response).

I suspect this behaviour might be dependant on how the app is being hosted. It looks like you're using the Google Cloud Run service, which I'm not familiar with, although I did come across this note in their docs:
> If the service performs background activities outside the scope of request handling it must use the [CPU always allocated](https://cloud.google.com/run/docs/configuring/cpu-allocation#choosing-background-execution) setting.

Hope this helps a little. If not, can you confirm how you're hosting your app, so I can try to reproduce the issue myself?

**Comment by gingertez** [comment]
Thanks Simon - I _am_ on Google Clour Run so that's a really interesting possibility - I'll investigate that.

However, I am puzzled (and hopefully I'll find the answer) because I can see from the logs that the request does complete (with a 200 response) but then the `OnCompleted` actions are not running. And more investigation has shown that further app mentions don't process either... until a slash command us used. So in testing I was able to build up a few 'pending' app mentions to be processed that then all got processed in one go when a slash command was used.

Also, I do have another service on Cloud Run that uses `services.AddHostedService<>` in `Program.cs`  that then runs every 20 minutes as a background service... and that works okay on Google Cloud Run.

I'll let you know what I figure out!

**Comment by gingertez** [comment]
@soxtoby your suggestion is right.

It is down to the fact that I've only got CPU allocated during processing and after your event handler has gone through the process of:
- instantiation of itself  and its injected services
- responding with an empty 200

_Then_ my handler is instantiated, along with it's injected  services, which takes a few seconds, So Google Cloud Run seems to suspend the thread/processing before the OnCompleted completes. I did notice in my investigations that _sometimes_ my handler got as far as logging out it's first "I'm here" log message. The reason I say it seems to "suspend" the processing is because then on the next request the first one continues while _that_ request is being processed.

I downloaded your code and played about with making it a synchronous call to my handler and that works but...
First request takes about 3.4 seconds to complete... which means Slack then re-requests using the same payload. The second time it goes through at about 600ms because the app isn't "starting up again".

Unfortunately that means the user sees two responses in their Slack app from only one app mention.

I have temporarily turned on "CPU always allocated" and it resolves the problem. But, it is an expensive option for a free Slack app (minimum options I can choose will cost $44 per month!)


Any thoughts on this are very welcome... any cheaper hosting providers I could use that would still respond quickly to Slack? Or seeing as I'm using Docker containers is there any way I could try to tell aspnet to 'auto start' and never stop opn idle so that the start up times are reduced?

**Comment by gingertez** [comment]
Closing the issue because it's not a particular problem with SlackNet itself, it's a more generic issue when combining ASPNET's propensity to go to sleep combined with Google Cloud Run's aggressive (rightly so) suspending of CPU processing when the request has completed.

For info I completely -emy app to make it as slim as possible, pushing the heavy work into another service, etc... and I still have an issue. Of course if my Slack App (which btw is for rendering PlantUML documents in Slack) ends up being popular then it won't be going to sleep very often :-)

**Comment by mblack-montag** [comment]
Just wanted to chime in with my experience.  I use Microsoft Azure for our cloud provider since we're a Microsoft centric business.  What you're describing sounds familiar.  If on a low or free pricing tier Azure services will sleep and then when needed will wake up which can take 3-5 minutes from a cold state.  One of the ways I fixed this was to run a service to ping the site like every five seconds.  Microsoft even had a way to enable this service but this was awhile ago.  I'm not sure about Google Cloud but that may be an option.  I use Azure Functions to host my SlackNet apps and these always seem hot even on the consumption tier.  You definitely need a service in a constant up state for incoming requests due to Slacks 3 second response requirement.

**Comment by soxtoby** [comment]
My experience has been similar to @mblack-montag's - you need to be able to response quickly to Slack's requests. The way Google Cloud Run suspends execution rather than stopping and starting the app _seems_ like it could work, but you'd need some way to let it know _when_ it can suspend.

The only other suggestion I can make, if you can't find a cheap enough hosting service, is to run the app locally with socket mode, which removes the requirement for a publicly accessible web site. Obviously doesn't help if you need it to be a website for other reasons, or if you don't have a local machine you can run it on 🤷.
