### ISSUE TITLE
MessageEvent not being handled (socket mode)

### ISSUE THREAD

**Issue by Joeb454** [soxtoby/SlackNet#125]
I’m having some issues with the latest NuGet version where the client doesn’t seem to handle MessagEvents from socket mode.

The handler at this point is virtually identical to this:
https://github.com/soxtoby/SlackNet/blob/master/Examples/NoContainerExample/Program.cs

I can see that the client connects via the socket, and even that it creates an instance of my message handler class, but it’s not hitting a breakpoint at the beginning of the handle method (or executing any of that code.

Any help on what this could be (suspect it’s my fault!) would be appreciated (and thanks ahead of time!)

**Comment by soxtoby** [comment]
Hi @Joeb454, have you subscribed to the event in your app on [api.slack.com](https://api.slack.com/)? You'll need to enable events for your app, and then subscribe to the `message.channels`, `message.groups`,  `message.im`, and `message.mpim` bot events (depending on which kind of conversations you want to subscribe to) to receive message events. Your app also needs to be added to the channel to receive messages from it.

Hope this helps.
