### ISSUE TITLE
MessageEvent Handler gets old messages repeatedly

### ISSUE THREAD

**Issue by feritzcan2** [soxtoby/SlackNet#126]
Hello, I'm using slacksocketclient.  Even if I dont add a message handler, message handler method gets triggered repeatedly.
Why its happening? MessageEvent seems to be bot_message. But why its triggered repeatedly? Should I send acknowledge messages to them? If so how? I couldnt find :(

![image](https://user-images.githubusercontent.com/55948243/205509407-4851068c-8cdd-4e11-b11e-c4309a92cdae.png)
![image](https://user-images.githubusercontent.com/55948243/205509459-38df8137-72a1-42bb-bde4-56e5c49cbbd6.png)

**Comment by soxtoby** [comment]
Hi @feritzcan2, are you saying your `MessageEventListener.Handle` method is being hit repeatedly even though it hasn't been registered, or just that "Handling message event" is being logged?

If it's the former, then that's quite surprising, and I'd need to see the code you're using to configure SlackNet to figure out why that might be.

If it's the latter, then that behaviour is normal - if you've subscribed your app to an event, then Slack will send your client those events regardless of whether you've registered any handlers. Those events _do_ need to be responded to, but SlackNet does that for you automatically, which is what the "Acknowledging request" logs are referring to. SlackNet then runs your registered handlers for the event and logs that list of handlers, which will be empty if no handlers have been registered.

Hope that helps.
