### ISSUE TITLE
Block Kit support

### ISSUE THREAD

**Issue by soxtoby** [soxtoby/SlackNet#13]
https://api.slack.com/block-kit

**Comment by Silvenga** [comment]
Do you mind if I take a whack at this feature?

**Comment by soxtoby** [comment]
Thanks for the offer, it's much appreciated! As it happens, I'm already part-way through implementing this. Should have something up this weekend.

**Comment by soxtoby** [comment]
Took a little longer than expected, but I think it's done. v0.3.0 now has block support.

**Comment by Silvenga** [comment]
Awesome! I also wanted to say @soxtoby, this is a wonderfully designed library.
