### ISSUE TITLE
Is it planned to implement sending messages by web hooks?

### ISSUE THREAD

**Issue by TimSon777** [soxtoby/SlackNet#140]
Or how else can it be?)

**Comment by TimSon777** [comment]
Wow thanks! Initially implemented via a dictionary, but your second way is awesome

**Comment by soxtoby** [comment]
Just pushed up v0.10.20 with a `PostToWebhook` method on `SlackApiClient`, so the code should now be as simple as:
```c#
var slackServices = new SlackServiceBuilder();
var client = slackServices.GetApiClient();
await client.PostToWebhook("<hook URL here>", new Message { Text = "Hello, world!" });
```
