### ISSUE TITLE
Support for isolated workers in azure functions

### ISSUE THREAD

**Issue by m1no** [soxtoby/SlackNet#144]
Hello, are there plans to support isolated worker runtimes in the future? This is Microsoft's preferred way for the future. I was unable to get the example code running.

**Comment by soxtoby** [comment]
Thanks for raising this, @m1no. I don't use Azure Functions myself, so this is the first I've heard of isolated worker runtimes. Looking at the documentation it seems the regular ASP.NET `HttpRequest` is no longer used, and Azure Function specific classes are used instead, which would make it difficult to integrate with existing code, and possibly requiring an additional package to account for the extra dependencies.

I'll try to look deeper into this in the next week or so to see if there's an easy way to support it, but chances are you're better off sticking with an in-process Function for now.

**Comment by soxtoby** [comment]
I spent a bit of time looking at this and unfortunately I don't think I can support it in the short term. The way requests are handled in isolated worker runtimes is too different to ASP.NET for me to be able to adapt the existing code.

I do want SlackNet to be flexible enough to support this scenario, so I'll aim to get this working at some point, but I can't provide any kind of timeline for a change like this.

**Comment by m1no** [comment]
Thanks, @soxtoby, for your response. I can see how this can be challenging, and I wanted to leave it here so that people know. Adding a hint to the documentation would help that Azure Function support is only partial.

**Comment by j5alive** [comment]
@soxtoby I'd be keen to contribute a solution to this issue if you're open to it? We're heavy users of Azure functions and finding ourselves slowly being pushed towards needing to run in .NET 8 which is isolated workers only at this stage. I was thinking that rather than trying to adapt the SLackNet.AspNetCore project to support Azure functions I could instead create a new Project/Package that provides the support for Azure Functions. Any thoughts on a good approach or recommendations?

**Comment by soxtoby** [comment]
To create a new project to support isolated worker functions without changing any SlackNet code, I think you'd need to basically copy the SlackNet.AspNetCore project and then change it to fit the different API.

I had a look at what was being used from `HttpContext` to see if I could extract out some interfaces so at least you wouldn't have to re-implement all of `SlackRequestHandler`. The sticking point seemed to be getting form data from the request, which `HttpRequestData` doesn't support, until I discovered that Microsoft recently released support for [ASP.NET Core integration](https://learn.microsoft.com/en-us/azure/azure-functions/dotnet-isolated-process-guide#aspnet-core-integration), which brings back most of the classes that SlackNet.AspNetCore relies on.

The net result is that adapting the existing code has suddenly become much easier. And now that I'm half-way down the rabbit hole, I figure I might as well keep digging, so I should have something within the next week.

**Comment by j5alive** [comment]
Awesome, yes this was the approach I was taking and using the ASP.NET Core integration as mentioned. Here is a draft PR #185 if you want to use anything I had started. With this approach I did hit an issue where the instance of `IServiceProvider` being set in the `SlackRequestContext` was being disposed of, so would cause errors. There is also a working Isolated worker example in the PR.

**Comment by soxtoby** [comment]
Thanks @j5alive, that PR definitely helped me with my own approach. The changes are now available on master with updated readme and example, in case you want a preview. Unfortunately I've hit a snag with the build system😫, so it'll probably be another day or two before I can release the new packages.

**Comment by j5alive** [comment]
Thanks, I'll pull latest and check it out.

**Comment by soxtoby** [comment]
Managed to get everything building again. Azure Functions support is now available in [v0.12.0](https://github.com/soxtoby/SlackNet/releases/tag/v0.12.0).
