### ISSUE TITLE
Message events always return 200 OK to Slack without waiting for handling or errors

### ISSUE THREAD

**Issue by diegosasw** [soxtoby/SlackNet#147]
I am running some automated tests where I post `event_callback` wrapping a message event (see below sample).

The problem I am finding is that it seems the POST to `/slack/event` (as if it was Slack posting it whenever something happens on the channel), receives a 200 OK empty string to aknowledge the reception, even if it fails to handle the event. It seems it's not awaiting the `IEventHandler<MessageEvent>`

For example, if I have the following handler
```
public class SlackEventHandler
    : IEventHandler<MessageEvent>
{
    private readonly ISlackApiClient _slack;
    
    public SlackEventHandler(ISlackApiClient slack) => _slack = slack;

    public async Task Handle(MessageEvent messageEvent)
    {
        await Task.Delay(10000);
        throw new SlackException("why wouldn't you wait??");
    }
}
```

Slack would still be receiving a 200 OK from SlackNet middleware and it doesn't wait for the result of the new message posting.

Is this per design? Is there any way to have handlers awaited before sending the 200 OK to slack?

Sample on how do I do this:
```
public static Task<HttpResponseMessage> PostAsSlackCallbackEvent<TEvent>(
    this HttpClient client,
    string requestUri, 
    TEvent value,
    string signingSecret = TestSettings.Slack.SigningSecret,
    string apiToken = TestSettings.Slack.ApiToken,
    CancellationToken cancellationToken = default)
    where TEvent : Event
{
    var json = JsonSerializer.Serialize(value, new JsonSerializerOptions(JsonSerializerDefaults.Web));
    
    var slackCallbackJson = "{\"token\": \"" + apiToken + "\", \"type\": \"event_callback\", \"event\":" + json + "}";
    var content = ToSlackContent(slackCallbackJson, signingSecret);
    return client.PostAsync(requestUri, content, cancellationToken);
}

private static StringContent ToSlackContent(string json, string signingSecret = TestSettings.Slack.SigningSecret)
{
    var timestamp = (int)DateTime.UtcNow.Subtract(new DateTime(1970, 1, 1)).TotalSeconds;
    var encoding = new UTF8Encoding();
    using var hmac = new HMACSHA256(encoding.GetBytes(signingSecret));
    var messageBytes = encoding.GetBytes($"v0:{timestamp}:{json}");
    var messageHash = hmac.ComputeHash(messageBytes);
    var signature = $"v0={string.Concat(messageHash.Select(b => b.ToString("x2")))}";

    var content = new StringContent(json, Encoding.UTF8, "application/json");
    content.Headers.Add("X-Slack-Request-Timestamp", timestamp.ToString());
    content.Headers.Add("X-Slack-Signature", signature);
    content.Headers.ContentType!.CharSet = string.Empty;

    return content;
}
```

**Comment by soxtoby** [comment]
Thanks for the question, @diegosasw. What you're seeing is by design - Slack expects events to be responded to within 3 seconds, and will retry after that, eventually disabling events completely if an endpoint can't keep up. There's nothing meaningful that can be returned from an event request, so SlackNet responds immediately before running any event handlers.

I'd recommend testing directly against your event handler class, which will be much simpler, and won't tie your tests to the details of how Slack sends requests; details which SlackNet is meant to be abstracting over.

**Comment by diegosasw** [comment]
Thanks for clarifying this.

While I agree the handling must be quick (less than 3 seconds), I also would see value in waiting, at least, to queue the event for async processing later on. The reason is because if for whatever reason queuing an event fails (e.g: message bus or persistence temporarily unavailable) slack wouldn't re-attempt to deliver the message event because it already got the 200 OK. It wouldn't happen often though.

In any case the library is great and I appreciate your work and time to reply!
