### ISSUE TITLE
Result of userprofile is null if fields is not present

### ISSUE THREAD

**Issue by calledude** [soxtoby/SlackNet#15]
`SlackApiClient.UserProfile.Get()` returns null if `Fields` isn't present in the result.

It tries to deserialize an array into a dictionary, which causes the JSON parser to freak out. This is evident when using `JsonConvert.DeserializeObject<UserProfileResponse>(string result)` instead of this: https://github.com/soxtoby/SlackNet/blob/28544a68160cf01b3dcd35e171d2ad436fd7c3d8/SlackNet/SlackApiClient.cs#L179
If `Fields` is empty/null, it'll throw, whereas `JObject.ToObject()` won't.

https://github.com/soxtoby/SlackNet/blob/28544a68160cf01b3dcd35e171d2ad436fd7c3d8/SlackNet/Objects/UserProfile.cs#L24

**Comment by soxtoby** [comment]
Thanks for the bug report. Slack is indeed returning an empty array if the profile doesn't have any custom fields set. I'll look into this and see what I can do.

**Comment by calledude** [comment]
I haven't looked too closely at it, but could it be related to the null-handling setting in the jsonserializer?

**Comment by soxtoby** [comment]
Seems like Slack is returning null for `Fields` when a user hasn't set anything in their profile, an empty array if they _have_ set something in their profile, but _not_ any custom fields, and an object if they've filled in any custom fields.

I've made a change to ignore arrays for the `Fields` property when deserializing, which is probably not very robust, but should be good enough for this edge case.

Please give v0.3.1 a go and see if that works.
