### ISSUE TITLE
TypedEventHandler has no access to EventCallback data

### ISSUE THREAD

**Issue by iamstudent-001** [soxtoby/SlackNet#150]
Hi 

I'm working on an slack app that needs to be able to be installed on multiple workspaces. This means I need to somehow be able to reference an incoming event to the workspaces that is sending the event. `EventCallback` has the data I need but it is not available in the handle method when using a TypedEventHandler. 
Is their any reason this isn't provided? Looking at the TypedAsyncBlockActionHandler the actual request is available in the handle method. 
![image](https://user-images.githubusercontent.com/125692096/227728399-be8bce33-0664-4c85-ae6e-747b799c514b.png)

But it the TypedEventHandler isn't doing this:
![image](https://user-images.githubusercontent.com/125692096/227728555-ae5d0b0a-5a21-47ab-8b0e-ec5b10767c44.png)

The only option I see currently is to handle the `EventCallback ` directly and write my own typed handlers who include the data I need.

Could you please advise? 

Thanks!
Arne

**Comment by soxtoby** [comment]
Thanks for the question, @iamstudent-001. If you need access to the whole `EventCallback`, I'd advise you use untyped handlers and check the type of `eventCallback.Event` in your handler. Unfortunately, providing the `EventCallback` to typed handlers would be a breaking change, which I'd prefer to avoid for now.

**Comment by cult-security-mikko** [comment]
Just to add a "Would use if available" +1 as we are experimenting currently with SlackNet as a possible solution for us and also need multi workspace support. Would be nice to have this but we will work around if this is too much of a breaking change from SlackNet POV.
