### ISSUE TITLE
How can I attach a png file in PostMessage method?

### ISSUE THREAD

**Issue by ohwwh** [soxtoby/SlackNet#151]
How can I attach a png file in PostMessage method? I set ImageUrl in Attachment but nothing shown..... is there anything I have to set also?

**Comment by soxtoby** [comment]
Hi @ohwwh, looks like you'll need to add something else to the attachment to get the image to show up, like a title or some text. As per [Slack's attachments docs](https://api.slack.com/reference/messaging/attachments) though, attachments are a legacy feature, and you'd be better off using an [image block](https://api.slack.com/reference/block-kit/blocks#image) instead, which won't require any extra text and will look cleaner in Slack.

You can post an image with an image block with code like this:
```c#
await slackApiClient.Chat.PostMessage(new Message {
    Channel = "#mychannel",
    Blocks = { 
        new ImageBlock {
            ImageUrl = "<image url here>",
            AltText = "<required text summary of image>"
        }
    }
});
```

Hope this helps.
