### ISSUE TITLE
Q: Rate limit

### ISSUE THREAD

**Issue by sommmen** [soxtoby/SlackNet#152]
Hiya,

I'm currently using SlackApi - however this library seems more maintained so i'm up for switching,
but have a question, does this allow me to handle rate limits in some way?

SlackApi does not expose the http response message so i cannot act on being rate limited.

**Comment by soxtoby** [comment]
Thanks for the question, @sommmen. SlackNet will automatically retry rate-limited API requests for you, using the delay provided by Slack. You can choose to handle it yourself if you want though, by setting `((SlackNet.SlackApiClient)slackApiClient).DisableRetryOnRateLimit = true;` (the property isn't exposed on the regular interface), and catching any `SlackNet.SlackRateLimitException`s that are thrown.

Hope that helps.

**Comment by sommmen** [comment]
> Thanks for the question, @sommmen. SlackNet will automatically retry rate-limited API requests for you, using the delay provided by Slack. You can choose to handle it yourself if you want though, by setting `((SlackNet.SlackApiClient)slackApiClient).DisableRetryOnRateLimit = true;` (the property isn't exposed on the regular interface), and catching any `SlackNet.SlackRateLimitException`s that are thrown.
> 
> Hope that helps.

Just migrated over, this works like a charm!
