### ISSUE TITLE
Q: Attach / Upload file to message

### ISSUE THREAD

**Issue by sommmen** [soxtoby/SlackNet#153]
Hiya,

Quick question, i can't really figure out how to upload a file together with a message.
I have some xlsx files i'd like to upload together with a message.

https://api.slack.com/methods/files.upload seems to only be able to push files into a channel, i'd like it linked to my message.

It should look something like this (note they lightgrey background over the whole message):
![image](https://user-images.githubusercontent.com/8641495/231464674-9d8fca3c-72dd-425b-99a5-ba517e7e36a5.png)

Is there any way to do this?

Currently i'm doing the following which does not produce the right result:

``` csharp
// SlackNet will handle retrying on rate limited api calls (indefinitely)
var response = await _slackApiClient.Chat.PostMessage(new Message
{
    Channel = channelId,
    Text = content,
    IconEmoji = iconEmoji,
    IconUrl = iconUrl,
    Username = botUserName,
    UnfurlLinks = unfurlLinks ?? default,
    Attachments = attachments ?? new List<Attachment>()
});

if (notificationAttachments is { Count: > 0 })
{
    foreach (var notificationAttachment in notificationAttachments)
    {
        var fileStream = File.Open(notificationAttachment.FileName, FileMode.Open);
        _ = await _slackApiClient.Files.Upload(fileStream, Path.GetExtension(notificationAttachment.FileName),
            Path.GetFileName(notificationAttachment.FileName), notificationAttachment.Name,
            channels: new[] { response.Channel });
    }
}
```
![image](https://user-images.githubusercontent.com/8641495/231456393-545d8909-c030-46af-b476-37289e89b267.png)

I also tried setting the channelId and ThreadTs - which produces the file as a reply (but not a singular message like i want)

**Comment by sommmen** [comment]
It seems like you can create a message, upload files, and then update the message with the file(s).

https://api.slack.com/methods/chat.update

However fileIds is missing from this library :/

**Comment by soxtoby** [comment]
Hi @sommmen, as far as I can tell there's no way to upload a file via the API and have it look exactly the same as when you do it through the Slack app - for whatever reason, they're using an undocumented API method to achieve this 🤷.

If you don't need the preview image, then you can specify the `initialComment` argument to `Files.Upload()` to provide a message. It supports markdown, but if you need something fancier you can update the message afterwards and specify the `Blocks` explicitly.

If you _do_ need the preview image, then it looks like you'll need to use the [remote files](https://api.slack.com/messaging/files/remote) API, which means hosting the files outside of Slack.

I'll add the missing `FileIds` property to `MessageUpdate` for completeness, but unfortunately it doesn't help with this, since it only lets you remove files from a message, or add them back to the same message they've been removed from. Adding file IDs to a different message has no effect.

Hope this helps.

**Comment by sommmen** [comment]
> Hi @sommmen, as far as I can tell there's no way to upload a file via the API and have it look exactly the same as when you do it through the Slack app - for whatever reason, they're using an undocumented API method to achieve this 🤷.
> 
> If you don't need the preview image, then you can specify the `initialComment` argument to `Files.Upload()` to provide a message. It supports markdown, but if you need something fancier you can update the message afterwards and specify the `Blocks` explicitly.
> 
> If you _do_ need the preview image, then it looks like you'll need to use the [remote files](https://api.slack.com/messaging/files/remote) API, which means hosting the files outside of Slack.
> 
> I'll add the missing `FileIds` property to `MessageUpdate` for completeness, but unfortunately it doesn't help with this, since it only lets you remove files from a message, or add them back to the same message they've been removed from. Adding file IDs to a different message has no effect.
> 
> Hope this helps.

Hey man, too bad and thanks for your thorough support.

**Comment by sommmen** [comment]
> Hi @sommmen, as far as I can tell there's no way to upload a file via the API and have it look exactly the same as when you do it through the Slack app - for whatever reason, they're using an undocumented API method to achieve this 🤷.
> 
> If you don't need the preview image, then you can specify the `initialComment` argument to `Files.Upload()` to provide a message. It supports markdown, but if you need something fancier you can update the message afterwards and specify the `Blocks` explicitly.
> 
> If you _do_ need the preview image, then it looks like you'll need to use the [remote files](https://api.slack.com/messaging/files/remote) API, which means hosting the files outside of Slack.
> 
> I'll add the missing `FileIds` property to `MessageUpdate` for completeness, but unfortunately it doesn't help with this, since it only lets you remove files from a message, or add them back to the same message they've been removed from. Adding file IDs to a different message has no effect.
> 
> Hope this helps.

I checked, but any chances this can be improved via the new remote file api's or not? :)

**Comment by soxtoby** [comment]
Yep looks like the new APIs do the job:

```csharp
await slack.Files.Upload(
    new FileUpload(@"C:\Countries.xlsx"),
    channelId: "C********",
    initialComment: "Upload test");
```

Produces:
![image](https://github.com/soxtoby/SlackNet/assets/1848926/fc0762bf-2754-4d56-9a24-7781b608723f)

**Comment by sommmen** [comment]
> Yep looks like the new APIs do the job:
> 
> ```cs
> await slack.Files.Upload(
>     new FileUpload(@"C:\Countries.xlsx"),
>     channelId: "C********",
>     initialComment: "Upload test");
> ```
> 
> Produces: ![image](https://private-user-images.githubusercontent.com/1848926/326738611-fc0762bf-2754-4d56-9a24-7781b608723f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ0NjgzOTIsIm5iZiI6MTcxNDQ2ODA5MiwicGF0aCI6Ii8xODQ4OTI2LzMyNjczODYxMS1mYzA3NjJiZi0yNzU0LTRkNTYtOWEyNC03NzgxYjYwODcyM2YucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQzMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MzBUMDkwODEyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NGQ2NTBiMGM3YzVjYzE4OTQ3NDQ2ODgzYjU4Y2UxNmQzMGMwMTMzZjgyODBhMzNiYWRkZTg2ZTliZWYxOTZhMyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.qT-D21hD9K9n3eRIUQBHB8aILwRD8EyUl-kPRhPZBtM)

Yeah that uses the 'initialcomment' not a seperate message, so that does not solve my issue.
From support i received:

> I believe if you want to get the desired result similar to the screenshot, you should update the file like described here: https://
> api.slack.com/methods/files.getUploadURLExternal#markdown
>  
> Then, you can use blocks to format the file into a message. Particularly, you'll want to use the file_object block. 
>  
> •	https://api.slack.com/reference/block-kit/composition-objects#slack_file
> •	https://api.slack.com/reference/block-kit/blocks#image_example

I'll fiddle with this myself, thanks for your time!
