### ISSUE TITLE
Can you install the socket based slacknet non-web demo on other workspaces?

### ISSUE THREAD

**Issue by edgiardina** [soxtoby/SlackNet#154]
Sorry to ask this in an issue, it might be that I don't understand the docs well enough.

Basically, the socket-based example works well when I build a new app from scratch and hook the slacknet example up. But if I want to expand and run the slacknet demo on another, second workspace, I'm not sure how to do that in a console/exe app. Is that possible? It appears when I retrieve an "install url" from slack there's always an OAuth process to install the app. However I'd prefer not to create an API and handle everything in a console app deployed to docker and running on websockets.

**Comment by soxtoby** [comment]
Slack only supports socket mode for a single instance at a time. If you want to install the app on multiple instances, then you'll need to use the [Events API](https://api.slack.com/apis/connections#events) via the `SlackNet.AspNetCore` package.

If you only want to connect to instances you have control over, then you _could_ create multiple Slack apps, connect to each of them separately by constructing multiple `SlackSocketModeClient`s, each with their own `CoreSocketModeClient`, using a different app-level token for each, but it'll get pretty hairy pretty quickly.

**Comment by edgiardina** [comment]
This is the answer I needed because it isn't explicit in slacks docs. TYVM

**Comment by edgiardina** [comment]
Sorry one more question @soxtoby ... does SlackNet.AspNetCore support the OAuth workflow for multiple workspaces? if so, what should my redirect URL be relative to my project's root URL?

**Comment by soxtoby** [comment]
SlackNet supports the [oauth.v2.access](https://api.slack.com/methods/oauth.v2.access) API method required to get an access token once you've got an authorization code, but there's not yet a built-in endpoint for receiving said authorization code, so you'll need to implement that yourself for now.

I haven't had to do this myself, so I can only point you to [Slack's OAuth documentation](https://api.slack.com/authentication/oauth-v2), which unfortunately is a little vague about what you can expect to receive at that endpoint.

Hope that helps.

**Comment by edgiardina** [comment]
It does help. I'm just having trouble wrapping my head around how Slacknet plugs into this after the OAuth flow.

I have the following program.cs

```
builder.Services.AddSlackNet(c => c
    // Configure the tokens used to authenticate with Slack
    .UseApiToken(slackSettings.ApiToken) // This gets used by the API client

    // Register your Slack handlers here
    .RegisterSlashCommandHandler<IfpaCommandHandler>(IfpaCommandHandler.SlashCommand)
);


var app = builder.Build();

// This sets up the SlackNet endpoints for handling requests from Slack
// By default the endpoints are /slack/event, /slack/action, /slack/options, and /slack/command,
// but the 'slack' prefix can be changed using MapToPrefix.
app.UseSlackNet(c => c
    // The signing secret ensures that SlackNet only handles requests from Slack 
    .UseSigningSecret(slackSettings.SigningSecret)    
    // You can enable socket mode for testing without having to make your web app publicly accessible
    .UseSocketMode(false)
);
```

And I can create an endpoint on my webserver that is the redirect URL, and receive the code in the querystring. and then I can call Slack's API to get a code. The confusing thing is, I get an access token, but how do I use it? Slack, after all, is calling ME via my API endpoints. 

```
public class OAuthController : ControllerBase
    {
        private string oAuthUrl => "https://slack.com/api/oauth.v2.access";

        [HttpGet]
        public async Task<IActionResult> OAuthRedirect(string code)
        {
           var result = await "https://slack.com/api/oauth.v2.access"
                .SetQueryParam("client_id", "")
                .SetQueryParam("client_secret", "")
                .SetQueryParam("code", code)
                .GetJsonAsync();

            //I have a token, but what do I do with it? Slack is calling me!
            var token = result.token;

            //Getting the user back to Slack is confusing, too. I want the user to install the app, approve, then I guess go back to slack, right?
            return Redirect("https://www.ifpapinball.com");
        }

    }
```

I think I am just missing something fundamentally obvious.

**Comment by soxtoby** [comment]
Once you've got the API token back from Slack, you'll need to store it somewhere so you can use it later. You can then use it for making API calls using the `WithAccessToken` method:
```c#
await slackClient.WithAccessToken(someToken).Chat.PostMessage(...);
```
Which token to use will depend on what your app is doing. If you're responding to events from Slack, I'd recommend using the non-generic version of `IEventHandler`, which gives you access to metadata about the event that you can use to identify which installation the event is coming from.
