### ISSUE TITLE
Public distribution support?

### ISSUE THREAD

**Issue by gilmatok** [soxtoby/SlackNet#156]
Is this available on SlackNet? In the official SDKs, you can register an "installation store" that stores/retrieves installations (incl. bot token) for authorizing requests from different workspaces.

Is this also available in SlackNet?

**Comment by soxtoby** [comment]
Not currently, no. I'll probably work on adding proper multi-installation support soon, but for now you'll need to implement the OAuth redirect endpoint and auth code storage yourself. See #154 for some more information.

**Comment by gilmatok** [comment]
Thanks @soxtoby .
