### ISSUE TITLE
SocketMode multiple connection configuration, SlackBot support?

### ISSUE THREAD

**Issue by ByteJuggler** [soxtoby/SlackNet#160]
(Being kind of new to SlackNet, and with apologies if there's a more appropriate place to ask this - if so please advise:)

In reference to SocketMode implementation (https://github.com/soxtoby/SlackNet/issues/67)
> The socket mode client will open 2 connections, with a 10 second delay between them so they don't expire at the same time. This is currently configurable only if you construct the client yourself, but I'll **_make the configuration easier before release._**

Was this ever done?  If so is there an example on how to configure it?  I've seemingly found that occassionally bot does not seem to have connection and would like to change/increase the connections/timings etc.

Also: It seems that the SlackBot classes provide a nice (more fluent) interface to bot type functionality while the SlackBot stuff (obviously) still uses the old (?) RTM code.

Am I missing something -- wouldn't it be useful/helpful to migrate the SlackBot code from RTM to SocketMode?  What is the key problem that makes this problematic/hard, or is it just lack of time/manpower?  Or am I just not familiar with the alternatives to see they're as easy to use for bot apps?  Eg I'm wondering whether it would be valuable to try and do the update/migration and learn something in the process, or whether it would be a waste of time.

**Comment by soxtoby** [comment]
Thanks for the questions, @ByteJuggler.

I did indeed add simpler configuration for the number of connections: the `ISlackSocketModeClient.Connect()` method takes in an optional `SocketModeConnectionOptions` argument, which lets you specify both the number of connections and the delay between opening them.

As for `SlackBot`, my current thinking is that it isn't worth updating. When I first wrote it, the RTM API was the only way to respond to messages in real-time without needing a public website, but the raw API was difficult to work with. The new socket mode client probably isn't quite as easy to use as the `SlackBot` client, but for what you lose in simplicity, you gain a lot in power: `SlackBot` was only able to handle message events, but the socket mode client can handle Slack's full range of event types.

A `SlackBot` equivalent for your specific use case might be useful, but I suspect a generic implementation would end up being a leaky abstraction that often _almost_, but _doesn't quite_ do what you need, and you'd end up having to use the core API anyway.

Hope that helps.
