### ISSUE TITLE
Use both BotToken and UserToken

### ISSUE THREAD

**Issue by Dionisos94** [soxtoby/SlackNet#161]
Hello,

First, this library is really really good ! It helped me a lot setuping a slack bot in C# so thanks a lot to you !

I have a little issue.
I have a SocketMode bot that needs to react to some questions given by my users. The bot replies with an answer to their question and ask the users to provide a Feedback as a reaction to its message (like a thumbsup emoji or thumbsdown).
For all that, I use a Bot Token with corresponding scopes I need.

I init the bot token with `builder.Services.AddSlackNet(c => {c.UseApiToken(bottoken)})` in Program.cs
Everything works fine !

I am now developing a new features that search messages with `ISlackApiClient.Search.Messages(string query)` function.
However, I hit an issue `not_allowed_token_type` which is normal because this function seems only to be available to user token with `search:read` scope.
I requested the scope and got a User token from slack.

However, I am not to sure how to use it in SlackNet. I can only setup 1 token with the function `UseApiToken(string token)`.
How can I do something like "when calling all other features, use the Bot-Token and when calling the search feature, use the User-Token" ?

I thought about creating 2 ISlackApiClient, 1 with the Bot-Token and 1 with the User-Token and calling the one I want on each feature but I would like your guidance on what would be the best way.
Thanks a lot !

**Comment by soxtoby** [comment]
Thanks for the question, @Dionisos94. `ISlackApiClient.WithAccessToken` is probably the way to go if you only need a user token in certain specific scenarios. It will return a new client rather than changing the configuration, so usage would look something like this:
```cs
var result = await client.WithAccessToken(userToken).Search.Messages(query);
```

Hope this helps.

**Comment by Dionisos94** [comment]
Thanks a lot @soxtoby !
I saw this function when I dug into the repo but I was not sure if it was the same type of token that was expected as parameter.
That helps a lot !
