### ISSUE TITLE
Is there a way to enable emojis for text input?

### ISSUE THREAD

**Issue by Tyler-V** [soxtoby/SlackNet#162]
![image](https://github.com/soxtoby/SlackNet/assets/3893234/7ec873a9-edd8-40fb-bc71-0fc95bd20234)

```
                new InputBlock
                {
                    Label = "Message",
                    BlockId = "message_block",
                    Optional = true,
                    Element = new PlainTextInput
                    {
                        ActionId = MessageInputActionId,
                        Placeholder = "What are you working on?"
                    }
                },
```

I have a modal I am showing and would like to enrich the user experience and allow them to select from the emojis and other formatting that is available in normal slack message - is this possible?

Thanks for the awesome library, its been fun playing with the options :)

**Comment by soxtoby** [comment]
Unfortunately, as far as I can tell from the [Slack documentation](https://api.slack.com/reference/block-kit/block-elements#input), there's no way to enable rich formatting in any input blocks - they're explicitly plain-text. For what it's worth though, you _can_ add native emojis using your OS's emoji picker, and Slack emojis that are typed out (e.g. `:tada:`) will render properly in any messages.

**Comment by Tyler-V** [comment]
Makes sense - I was able to figure that part out at least (availability in the image), not a deal breaker for us but good to know thanks!
