### ISSUE TITLE
Newtonsoft.Json.JsonReaderException

### ISSUE THREAD

**Issue by TimSon777** [soxtoby/SlackNet#164]
Hello! The following error occurs intermittently: **Newtonsoft.Json.JsonReaderException Unterminated string. Expected delimiter: ". Path 'event.view.app_id', line 1, position 3410-3415** (one of these numbers). We use only two events: `AppHomeOpened` and `AppUninstalled`. I assume that the problem is related to `AppHomeOpened`, because which crashes more often than we reinstall workspaces, maybe you know if this is a Slack problem or not?

**Comment by TimSon777** [comment]
![image](https://github.com/soxtoby/SlackNet/assets/90468548/ffaaf6c5-89b6-4e55-b6c7-82f8de490ce7)
Error here

**Comment by soxtoby** [comment]
Hi @TimSon777, `JObject.Load` should work with valid JSON of any shape, so my hunch would be that the request body is being truncated for some reason, before it gets as far as being deserialized. How are you hosting the app (e.g. console app with socket mode, locally hosted ASP.NET app etc.)?

It might be worth enabling logging in SlackNet (see the [release notes](https://github.com/soxtoby/SlackNet/releases/tag/v0.10.0) for info) and logging the `Data` and/or `Serialization` categories to help track down the issue.

**Comment by TimSon777** [comment]
I'm using an ASP.NET Core app hosted in cloud services. We caught this error using Sentry, it crashes approximately every 2-10 days. Not using Socket Mode

I looked at the code, it seems like your logger logs only outgoing requests, not incoming. So `Data` not works

Serialization not write wrong json
![image](https://github.com/soxtoby/SlackNet/assets/90468548/5944490b-cc9f-4c26-bedf-048f330691e4)

**Comment by soxtoby** [comment]
I'm a little confused by that error, because SlackNet shouldn't be trying to deserialize your `TestController.A` class in the first place. Are you inadvertently sending non-Slack requests to the SlackNet endpoints?

It's a pity that the failed JSON isn't being logged - I'll have to find some way to enable that. In the meantime, you could try enabling [HTTP logging in ASP.NET](https://learn.microsoft.com/en-us/aspnet/core/fundamentals/http-logging/) to help track down the problem.

**Comment by TimSon777** [comment]
I just used your code to see what logs would be printed on a failed deserialization (I configured the serialization like you). 
![image](https://github.com/soxtoby/SlackNet/assets/90468548/31c3c64a-5994-4158-a8b6-6845c8a33149)

I tried `context.Request.EnableBuffering` in the middleware, after which I tried to log incoming json, but failed with an `ObjectDisposedException` that is thrown when you read from request [link](https://stackoverflow.com/questions/67046879/system-objectdisposedexception-cannot-access-a-closed-stream-on-http-post-put-i)

**Comment by soxtoby** [comment]
I've put up [a new release](https://github.com/soxtoby/SlackNet/releases/tag/v0.11.1) that will log the request body before deserializing events. Give that a try and see what you get. It should be easier to enable `Data` logs now as well if you're using the default logger in ASP.NET.

**Comment by TimSon777** [comment]
Thanks a lot!
