### ISSUE TITLE
SubType = null on MessageEvent ?

### ISSUE THREAD

**Issue by Dionisos94** [soxtoby/SlackNet#165]
Hello,

I try to add a new feature to my slackbot to be able to interact with the previous message a user posted.

i.e a user post "Can you check this object is in database ?",
On the same thread, I then write a message ".check" and the bot should be able to retrieve the previous message to act on it (i.e retrieve the object id and do a sql query)

I was hoping to use my MessageEvent handler and just look at the subType property to check if it is a MessageReplied type to then cast it and be able to access the previous message.

However, when I try it, my reply SubType is null
Is that an expected behavior ?

![image](https://github.com/soxtoby/SlackNet/assets/15048957/5d2ffd06-02d3-4e47-a547-1fd2bd12b70e)

![image](https://github.com/soxtoby/SlackNet/assets/15048957/b427d08c-b398-4fe2-86dc-d97fd302149a)

SlackNet version: 0.10.24

Thank you !

**Comment by soxtoby** [comment]
Turns out this is a known issue on Slack's end. Per the [`message_replied`](https://api.slack.com/events/message/message_replied) event documentation:
> **Bug alert!** This event is missing the `subtype` field when dispatched over the Events API. Until it is fixed, examine message events' `thread_ts` value. When present, it's a reply. To be doubly sure, compare a `thread_ts` to the top-level `ts` value, when they differ the latter is a reply to the former.

Other message subtypes should still work as expected - looks like it's just `message_replied` that has different behaviour.

Hope this helps.

**Comment by Dionisos94** [comment]
Thanks mate !
A shame it is not yet fixed on their end :(
