### ISSUE TITLE
Missing SnoozeEndTime when SetSnooze

### ISSUE THREAD

**Issue by kurobirds** [soxtoby/SlackNet#166]
When I call SetSnooze within 30 minutes, I can get SnoozeRemaining but SnoozeEndTime is default value.

Here response in Slack API:
![image](https://github.com/soxtoby/SlackNet/assets/20903125/315c678b-8f81-4d16-995e-281d49ac5d49)

Here is response when I call SetSnooze function:
![image](https://github.com/soxtoby/SlackNet/assets/20903125/abc2a185-075c-4feb-9cf2-cee6fead45b7)

**Comment by soxtoby** [comment]
Thanks for raising this, @kurobirds. Looks like a minor typo - I'll have a fix up soon.
