### ISSUE TITLE
Error dispatch_failed in slack when execute command

### ISSUE THREAD

**Issue by ezarzone** [soxtoby/SlackNet#168]
Hello,

First, this library is really really good ! It helped me a lot setup a slack app in C# so thanks a lot to you !

When a command takes a while, Slack fails and does not send the response. Is there a way to avoid it?
Regards,

    public async Task<SlashCommandResponse> Handle(SlashCommand command)
    {
        Console.WriteLine($"{command.UserName} used the {SlashCommand} slash command in the {command.ChannelName} channel");
        // API call and process.  May take up to 10 seconds

        return new SlashCommandResponse
        {
            Message = returnMessage
        };
    }

**Comment by soxtoby** [comment]
Thanks for the question, @ezarzone. Seems like you may have already found the answer, which is to register an async handler, and respond before doing any lengthy processing. Your example would end up looking something like this:

```c#
public async Task Handle(SlashCommand command, Responder<SlashCommandResponse> respond)
{
    Console.WriteLine($"{command.UserName} used the {SlashCommand} slash command in the {command.ChannelName} channel");

    var returnMessage = GetConfirmationMessage(); // Quickly-built message to confirm the slash command was received

    await respond(new SlashCommandResponse
    {
        Message = returnMessage
    });
    
    // API call and process.  May take up to 10 seconds
}
```

From [your comment](https://github.com/soxtoby/SlackNet/issues/44#issuecomment-1715450168) in the early-response API, it seems like you might be trying to send another message after the longer-running API call has complete. This will work just fine, but unlike responding to the slash command request, you'll need to specify where the message is being sent to.

e.g.
```c#
await _slackApiClient.Chat.PostMessage(new Message
{
    Channel = command.ChannelId, // You can use the slash command's channel, or some other channel if you want
    Text = $"Here's what you asked for:"
});
```

Note that while the async handlers API is still considered "experimental", there should only be one breaking change before release, which should be fairly minor.

Hope that helps.

**Comment by ezarzone** [comment]
Thanks @soxtoby !!!
Since it is a command I would not like to respond to the channel but directly to the person, is it possible? 
In the end the response does that, responds in the channel but only the person can see it. 

```
await _slackApiClient.Chat.PostMessage(new Message
{
    Channel = command.ChannelId, // You can use the slash command's channel, or some other channel if you want
    Text = $"Here's what you asked for:"
});
```

Another option would be to update the initial message? Can you think of how to do it? I had come to respond to the channel but of course the idea is to do it privately.

Regards,

**Comment by ezarzone** [comment]
PostEphemeral :)
