### ISSUE TITLE
Is there a "right" way to ignore the app's own messages?

### ISSUE THREAD

**Issue by Regenhardt** [soxtoby/SlackNet#172]
If in the [PingDemo](https://github.com/soxtoby/SlackNet/blob/master/Examples/SlackNetDemo/PingDemo.cs) it responded with "ping" again, it would trigger an endless loop, right?

I could of course check the UserId of the app and put that into my program as an ignored user, but that seems too manual.   
I could, each time my handler get a call to `Handle`, call slackApi.Auth.Test().Result.UserId but that just feels like unreasonably spamming Slack's API.  
Could do once and set a static field, then each call check if the static field is already set, but this also feels like there should be a better way to initialise things once on startup, I just haven't found it yet.

**Comment by soxtoby** [comment]
I would say the "right" way would be to check the message's `BotId` against the `BotUserId` returned during the [OAuth installation flow](https://api.slack.com/authentication/oauth-v2). If your app isn't being installed on other people's workspaces, then I'd suggest reading the bot ID from configuration, and checking against the message's `BotId`.

I should probably note that the `BotId` property was only just added in the latest release ([v0.11.3](https://github.com/soxtoby/SlackNet/releases/tag/v0.11.3)).

Hope that helps.

**Comment by Regenhardt** [comment]
Reading from config means manually getting the bot ID from Slack and adding it to the config? Or does SlackNet have its own config object I can read? I'd like to avoid a solution where I have to manually copy an ID from slack to the application.

I'm going with the static field version for now, seems the easiest and doesn't waste ressources:  
```
private static string? botUserId;
public async Task Handle(MessageEvent slackEvent)
{
    botUserId ??= (await slack.Auth.Test()).UserId;

    if (slackEvent.User == botUserId)
    {
        return;
    }
```

**Comment by soxtoby** [comment]
Reading from config would indeed mean manually getting the bot ID from Slack. For an internal app, I don't see it being much different to manually copying the API key to a config, but what you've got seems perfectly fine 👍
