### ISSUE TITLE
how to mock properties of ISlackApiClient for unit testing

### ISSUE THREAD

**Issue by wagnerteixeira** [soxtoby/SlackNet#173]
how to mock Chat, Conversations or anywhere property of ISlackApiClient for unit testing?

**Comment by soxtoby** [comment]
Hi @wagnerteixeira, it's a little difficult to provide specific advice here without knowing what mocking library (if any) you're using, or what kind of tests you're trying to write, but `ISlackApiClient` and all the types its API properties provide are interfaces, so if you're using a mocking library, you can configure a mock `ISlackApiClient` to return a mock `IChatApi` for its `Chat` property for example, and then configure that `IChatApi`'s `PostMessage` method to return the response that you need, or to test that the right `Message` was passed in.

Alternatively, you could implement your own `ISlackApiClient` for testing, which could expose the things you need for your tests. An example implementation might look something like this:

```c#
class TestSlackApiClient : ISlackApiClient
{
    public IChatApi Chat { get; set; }
    // ... other APIs and methods
}

class TestChatApi : IChatApi
{
    public async Task<PostMessageResponse> PostMessage(Message message, CancellationToken? cancellationToken = null)
    {
        PostMessageRequest = message;
        return PostMessageResponse;
    }
    
    public Message PostMessageRequest { get; set; }
    public PostMessageResponse PostMessageResponse { get; set; }
    
    // ... other methods
}
```

In your tests, you could then construct a `TestChatApi` and `TestSlackApiClient` to return the response you need, and access the `Message` that was passed in:
```c#
public void TestMessaging()
{
    var chatApi = new TestChatApi { PostMessageResponse = new PostMessageResponse() };
    var slackClient = new TestSlackApiClient { Chat = chatApi };
    var testClass = new MyTestClass(slackClient);

    testClass.DoTheThing();
    
    Assert.Equal("Expected message", chatApi.PostMessageRequest.Text);
}
```

Hope this helps.

**Comment by wagnerteixeira** [comment]
thank you very much for your reply!

in my use case i register ISlackApiClient using IServiceCollection.AddSlackNet and receive ISlackApiClient in handler as follows: 

```csharp
builder.Services.AddSlackNet(c => 
                c.UseApiToken(applicationConfig.Slack.AccessToken)
                .RegisterEventHandler<MessageEvent, MessageHandler>()
 );
 ```
 
 and event is

```csharp
public class MessageHandler : IEventHandler<MessageEvent>
{
    private readonly ISlackApiClient _slackApiClient;

    public MessageHandler
    (
        ISlackApiClient slackApiClient
    )
    {        
        _slackApiClient = slackApiClient;
    }

    public async Task Handle(MessageEvent slackEvent)
    {
        await _slackApiClient.Chat.PostMessage(new Message
        {
            Text = "pong",
            Channel = slackEvent.Channel,
            ThreadTs = slackEvent.EventTs
        });                
    }
}
```
on this way for moq i could implement a fake class for ISlackApiClient, but i change event handler to receive IChat on handler and inject IChat this way 

```csharp
 builder.Services.AddScoped<IChatApi>(prov => prov.GetRequiredService<ISlackApiClient>().Chat);
 ```

and handler is

```csharp
public class MessageHandler : IEventHandler<MessageEvent>
{
    private readonly IChatApi _chatApi;
    public MessageHandler
    (
        IChatApi chatApi
    )
    {        
        _chatApi = chatApi;
    }

    public async Task Handle(MessageEvent slackEvent)
    {
        await _chatApi.PostMessage(new Message
        {
            Text = "pong",
            Channel = slackEvent.Channel,
            ThreadTs = slackEvent.EventTs
        });                
    }
}
```

on this way i moq IChat with ```Mock<IChatApi> chatApiMock = new();``` and Setup this and pass to handler, its work for me

i dont now if is the best way...but works rs

thank you!
