### ISSUE TITLE
BlockOptionsRequest.View is missing

### ISSUE THREAD

**Issue by nimoskovE** [soxtoby/SlackNet#175]
Hi, 

Could you please add View to BlockOptionsRequest?
I have dependent menu selections and I need to be able to get the values of other menus.

According to the documentation it should be available:
https://api.slack.com/reference/interaction-payloads/block-suggestion

Thanks

**Comment by soxtoby** [comment]
Now available in [v0.11.4](https://github.com/soxtoby/SlackNet/releases/tag/v0.11.4).
