### ISSUE TITLE
PostEphemeral does not return the type PostEphemeralResponse

### ISSUE THREAD

**Issue by matthawley** [soxtoby/SlackNet#183]
The current implementation of `PostEphemeral` returns `PostMessageResponse`, which does not give access to the correct response and access to `MessageTs` contained within `PostEphemeralResponse`.

https://github.com/soxtoby/SlackNet/blob/1ceb8ff38401e36d5973494656d00cd269d8f65d/SlackNet/WebApi/ChatApi.cs#L66

**Comment by soxtoby** [comment]
The fix is now available in [v0.12.0](https://github.com/soxtoby/SlackNet/releases/tag/v0.12.0).
