### ISSUE TITLE
Can't send Http request in IEventHandler

### ISSUE THREAD

**Issue by TimSon777** [soxtoby/SlackNet#187]
Hi! We have very strange problem: we can't send http request in Api, where we locate this IEventHandler from IEventHandler (monolith with slack api and business-logic api), because we always get error: 

Microsoft.AspNetCore.Server.Kestrel.Core.BadHttpRequestException
Unexpected end of request content.

![image](https://github.com/soxtoby/SlackNet/assets/90468548/3cac8b15-3e94-4b81-80ff-7c98faa0c7fe)

I research it, and we can send these http requests in IBlockActionHandler and custom controllers too:

![image](https://github.com/soxtoby/SlackNet/assets/90468548/e2daea8f-13e0-4696-bdc9-02044de17e21)

Main difference between these actions: the former respond instantly and process this event in the background, while the latter process it in the moment

I also research it in github and find: https://github.com/dotnet/aspnetcore/issues/23949

![image](https://github.com/soxtoby/SlackNet/assets/90468548/612908b7-fdca-40a3-a568-9be3b93efe82)

You have something similar in your code, but everything seems ok. I'm a little confused by OnCompleted in HttpResponse, of course, but it seems to be normal there too. Any ideas?

**Comment by soxtoby** [comment]
Hmm... this _is_ strange. I agree the early response with events is potentially suspect, but I haven't had any luck reproducing the issue. By the time the event handler is called, nothing should be accessing the request as far as I can tell.

Is it definitely throwing during the `PostAsJsonAsync` call? Could it be something to do with the `IHttpClientFactory` configuration? I just used a plain `.AddHttpClient()` call to set it up.

**Comment by TimSon777** [comment]
Sorry, I forgot to provide context. This works locally, but specifically in aws apprunner it does not work. I just thought maybe you know some subtle places in your code that could potentially break something

I used `services.AddHttpClient();` too

**Comment by soxtoby** [comment]
> specifically in aws apprunner it does not work

This could be similar to what I hit with Azure Functions then - the app is only meant to run for the length of the request, and handlers running after the request completes were failing. I'm not familiar with App Runner, but if it operates similarly, then the solution may be the same - delay the response until the handler has completed.

Unfortunately I only put that functionality into the Functions integration - I'll try to get a new version up in the next few days that provides the same option for ASP.NET.
