### ISSUE TITLE
Issue with ReactionAdded Event

### ISSUE THREAD

**Issue by MuffinEHG** [soxtoby/SlackNet#190]
Hey all!  First of all, love the lib!

I am trying to write an event that does something with a message when it is reacted to.

I have this:
```
public class ReactionEvent(
    ISlackApiClient slack,
    ILogger<ReactionEvent> logger) : IEventHandler<ReactionAdded>
{
    public async Task Handle(ReactionAdded slackEvent)
    {
        logger.LogInformation("Received reaction - {Event}", JsonSerializer.Serialize(slackEvent));
    }
}
```

DI like this:
```
.RegisterEventHandler<ReactionAdded, ReactionEvent>()
```

But nothing is being logged.

I have TONS of other events (Message), slack commands, modals, etc - and they all work great (including the logging) - so I am having trouble figuring it out =)

**Comment by soxtoby** [comment]
Hi @MuffinEHG, the most likely problem is that you haven't subscribed your app to the `reaction_added` event via the [Slack apps interface](https://api.slack.com/apps).

Hope this helps.

**Comment by MuffinEHG** [comment]
> Hi @MuffinEHG, the most likely problem is that you haven't subscribed your app to the `reaction_added` event via the [Slack apps interface](https://api.slack.com/apps).
> 
> Hope this helps.

I have the event subscriptions setup, the app has the scopes and has been installed just fine.
![image](https://github.com/soxtoby/SlackNet/assets/135793449/dc1e337f-cd68-4065-b66c-bb407e1f4412)

It is still not working :(

**Comment by soxtoby** [comment]
Hmmm... I've tried adding your code to the [AspNetCoreExample](https://github.com/soxtoby/SlackNet/tree/master/Examples/AspNetCoreExample) project, and it's working fine. There must be something else going on on your side.

Assuming you're using SlackNet.AspNetCore, I'd suggest increasing the logging level and checking that the `reaction_added` event is being received. You can get SlackNet to log the data it receives by adding the following to your `appsettings.json` file:
```json
"Logging": {
  "LogLevel": {
    "SlackNet.Data": "Trace"
  }
}
```

If you're not using SlackNet.AspNetCore, then you'll need to register your own logger using SlackNet's `UseLogger()` configuration method. You can use the [MicrosoftLoggerAdaptor](https://github.com/soxtoby/SlackNet/blob/master/SlackNet.AspNetCore/MicrosoftLoggerAdaptor.cs) as an example implementation.
