### ISSUE TITLE
415 unsupported media type on Action

### ISSUE THREAD

**Issue by JenPullUp** [soxtoby/SlackNet#193]
I am using SlackNet.AspNetCore in API mode (without sockets)

When pressing a button in slack it shows this:
![image](https://github.com/soxtoby/SlackNet/assets/63970043/1068d5ae-075b-4b78-9c1a-5afeb1d3b09f)
Backend returns this debugging message:
![image](https://github.com/soxtoby/SlackNet/assets/63970043/73892548-784d-4456-8292-5625791272db)

i used the ModalViewHandler from example folder

**Comment by soxtoby** [comment]
Hi @JenPullUp. To handle button actions, in the Interactivity & Shortcuts section of your Slack app configuration, you'll need to point Slack at your web app's `/slack/action` endpoint instead of the `/slack/event` endpoint.

Hope that helps.

**Comment by JenPullUp** [comment]
ahh that makes sense! thanks i changed it and now i get a 404, i am just using your example for opening a modal and pressing a button, i didn't change anything else. i get these errors:
![image](https://github.com/soxtoby/SlackNet/assets/63970043/af8b87f3-c586-4fdf-8008-9a771eb2b370)

is there any documentation i am missing which can help me?

**Comment by soxtoby** [comment]
I couldn't reproduce this locally, but if you can inspect the `SlackException` that's being thrown, its `ErrorMessages` property should provide the path to the invalid argument. Alternatively, you can update to the [latest version of SlackNet](https://github.com/soxtoby/SlackNet/releases/tag/v0.12.3), which includes those error messages in the main exception message.

**Comment by soxtoby** [comment]
Happy to help - glad you got it working 👍

**Comment by beneton2003** [comment]
Hello everyone! I encountered a similar problem when integrating your component, please add this point to the user manual since I spent quite a lot of time and accidentally stumbled upon this article. For many users, this will be quite non-obvious. Thank you for your work. Have a nice day guys.
