### ISSUE TITLE
Need recommendations for deploying SlackNet App in int, stg, and prod env

### ISSUE THREAD

**Issue by mousliiim** [soxtoby/SlackNet#195]
Hello, first of all, thank you for this very cool library to use ;) 

I am working on a Slack app and the deployment of my application goes through several env: 

integration, staging. When it is in staging, the integration is no longer deployed, but in prod, the staging still has an open instance. I have two apps running on the client side (the app is in prod but it is therefore also run in staging) on Slack, Do you have anything to recommend? I am using interactions and connecting via socket !

Thanks

**Comment by mousliiim** [comment]
When I have two apps with the same API keys, only the home app works, but the event handlers for messages and app mentions don't work.

**Comment by soxtoby** [comment]
Hi @mousliiim. I'd recommend setting up separate Slack apps for separate environments. This will make sure events get sent to all your instances, and let you configure the apps differently. It _can_ be annoying having multiple apps responding to you, but you can avoid this by e.g. adding the separate apps to separate channels, or requiring a "test:" prefix in messages, and things like that.

Slack introduced a [manifests feature](https://api.slack.com/reference/manifests) not too long ago that looks like it would help with migrating config between environments. I haven't tried it myself, and its APIs haven't been added to SlackNet yet, but it might be useful anyway.

Hope that helps.
