### ISSUE TITLE
BlockAction doesn't contain 'Value' field

### ISSUE THREAD

**Issue by Lera919** [soxtoby/SlackNet#197]
**Issue Description:**

Using the SlackNet library, I've encountered an issue related to handling block actions of type button. It seems that while the library allows us to define a `value` property for button elements through the `Button` class, there's no straightforward way to access this `value` property when handling block actions using the `BlockActionRequest` class.

**Steps to Reproduce:**

1. Send a block action payload to Slack containing a button element with a `value` property.
2. Attempt to retrieve this `value` property from the `BlockActionRequest` object within the SlackNet library.

**Expected Behavior:**

Expected that the SlackNet library would provide a convenient way to access the `value` property of button elements in block action payloads.

**Actual Behavior:**

Current implementation of the `BlockActionRequest` class doesn't expose the `value` property. This makes it challenging to access the value associated with button elements when handling block actions.

**Additional Information:**

It's possible to manually parse the request and extract the `value` property from the payload JSON via HttpRequest.

```csharp
public class BlockActionRequest : InteractionRequest
{
    public Container Container { get; set; }
    public string TriggerId { get; set; }
    public MessageEvent Message { get; set; }
    public ViewInfo View { get; set; }
    public ViewState State { get; set; }
    public IList<BlockAction> Actions { get; set; } = [];
    [JsonIgnore]
    public BlockAction Action => Actions.First();
}

public class BlockAction
{
    public string Type { get; set; }
    public string ActionId { get; set; }
    public string BlockId { get; set; }
    public string ActionTs { get; set; }
    [JsonIgnore]
    public DateTime? ActionTimestamp => ActionTs.ToDateTime();
    
    // Missing property value
    public string Value { get; set; }
}
Code part was not tested

**Comment by soxtoby** [comment]
Thanks for raising this, @Lera919; it seems like a simple oversight on my part. I'll get something up in the next few days that can deserialize button values.

**Comment by soxtoby** [comment]
On further investigation, it seems I misunderstood the issue. `BlockAction` is the base class for a range of different types of actions that have different properties. One of those types is `ButtonAction`, which already has a `Value` property. So if you cast the `BlockAction` to a `ButtonAction`, you'll get access to the value you need.

Alternatively, if you register your action handler as a `IBlockActionHandler<ButtonAction>`, the `Handle` method will receive a `ButtonAction` as its first parameters. See [CounterDemo](https://github.com/soxtoby/SlackNet/blob/master/Examples/SlackNetDemo/CounterDemo.cs) and [it's registrations](https://github.com/soxtoby/SlackNet/blob/1856c18083a8639fe88c8ba4b46ed4b139b53514/Examples/SlackNetDemo/Program.cs#L28) for an example.

Hope this helps.
