### ISSUE TITLE
Missing new files.upload methods

### ISSUE THREAD

**Issue by agustinradami** [soxtoby/SlackNet#198]
Hi I noticed here that the files.upload method is being deprecated and replaced with this two new methods [files.getUploadURLExternal] and [files.completeUploadExternal].
(link https://api.slack.com/methods/files.upload)
It would be very nice to have support of this.
Best Regards,
Agustin

**Comment by soxtoby** [comment]
Thanks for raising this @agustinradami. I'll be adding support for this method of uploading soon.

**Comment by soxtoby** [comment]
The new methods are now available in [v0.13.1](https://github.com/soxtoby/SlackNet/releases/tag/v0.13.1), along with a couple helper methods to make them easier to use.
