### ISSUE TITLE
Add missing Pronouns to UserProfile 

### ISSUE THREAD

**Issue by samoreque** [soxtoby/SlackNet#200]
It would be great if we can access to the `pronouns` when we call  `_slack.Users.List()` for` SlackNet.AspNetCore`

thanks
Samuel

PD: Or is there a way to get pronouns?? 🤔

**Comment by soxtoby** [comment]
Thanks for raising this, @samoreque. I've added the missing `Pronouns` property to `UserProfile`, along with some other properties  that seemed to be missing, and I'll try to push up a new release soon with the changes.

**Comment by samoreque** [comment]
Thank you so much, excited to see the new version soon 💯

**Comment by soxtoby** [comment]
The new properties are now available in [v0.13.1](https://github.com/soxtoby/SlackNet/releases/tag/v0.13.1).

**Comment by soxtoby** [comment]
Seems like the changes to `UserProfile` broke deserialization - should be working now in [v0.13.2](https://github.com/soxtoby/SlackNet/releases/tag/v0.13.2).

**Comment by samoreque** [comment]
thanks for the heads up, going to test it
