### ISSUE TITLE
Users.list Profile - null

### ISSUE THREAD

**Issue by SmartlyGit** [soxtoby/SlackNet#201]
Hi, after updating to v0.13.1 we can't get the user profile from the User list.

Version 0.13.0 works well. We are able to get User list with Profile(Email...) information.

Were there any modifications or reason why it doesn't work in the latest version? Thanks.

**Comment by soxtoby** [comment]
Thanks for raising this - I'd added a new property to `UserProfile`, but messed up the type. Should be fixed in [v0.13.2](https://github.com/soxtoby/SlackNet/releases/tag/v0.13.2).
