### ISSUE TITLE
Silent failure when using SocketMode in AspNetCore with an invalid app level token

### ISSUE THREAD

**Issue by kikaragyozov** [soxtoby/SlackNet#205]
`AspNetCoreExtensions.UseSlackNet` calls Connect() method without `await`-ing its result, which is fine, as long as the task running handles its exceptions.

In .NET Framework 4.0, a `TaskScheduler.UnobservedTaskException` would be thrown when GC kicks in, and would completely crash the application. I set logging to `Debug` level, and still, got no feedback at what was going on. Worst of all - Slack itself does not report what went wrong when you use an interactive element in a message and reports an error with its transparent warning symbol - hovering over the symbol, you get no message, which is usually not the case.

I suggest proper logging and handling of exceptions is added to the `Connect` method. The error received was `invalid_auth`. For some reason my app level token became invalid, even though I've not modified it in any way, shape, or form.

**Comment by soxtoby** [comment]
Thanks for raising this, @kikaragyozov. I'll add logging around the initial connection to pick this sort of thing up, and see if I can find a better way to start the socket connection than just firing it off in a configuration method.

**Comment by kikaragyozov** [comment]
> Thanks for raising this, @kikaragyozov. I'll add logging around the initial connection to pick this sort of thing up, and see if I can find a better way to start the socket connection than just firing it off in a configuration method.

No worries! Any updates on this?

**Comment by soxtoby** [comment]
Thanks for the reminder, @kikaragyozov - I had this on my list, but had kind of forgotten about it. I've started working on this now and should have something in the next week or so.

**Comment by soxtoby** [comment]
New socket mode logic is available in [v0.14.0](https://github.com/soxtoby/SlackNet/releases/tag/v0.14.0). 

The socket mode client is now managed by an `IHostedService` when enabled with `UseSocketMode` in ASP.NET so its lifetime is properly managed by the application, and it logs an error when Slack returns an error response in the initial connection. Subsequent errors or disconnections will be logged at the debug level.

This turned into a non-trivial refactor of the web socket connection logic, which can be tricky to properly test, so please let me know if anything goes wrong.
