### ISSUE TITLE
Enable passing state to event handler instance

### ISSUE THREAD

**Issue by tahasi** [soxtoby/SlackNet#206]
My MessageEvent event handler has a dependency that I hope to pass to the constructor every time it is created in response to a Slack message event. Unfortunately, the `RegisterEventHandler` methods do not provide a means to pass state that needs to passed to the event handler when constructed.

Is there a recommendation of passing custom parameters to the message event handler when it is constructed?

For instance, how may the PingDemo class be extended to enable it to receive a pool of SQL connections to be used when handling event notifications?

**Comment by soxtoby** [comment]
Hi @tahasi, the event handlers are resolved from the DI container for each event, so if you've registered your connection pool with the container, you should be able to add it to the constructor of your event handler.

For example, to add a connection pool to the PingDemo, the constructor would be changed to something like:

```csharp
public PingDemo(ISlackApiClient slack, ISqlConnectionPool connectionPool)
{
    _slack = slack;
    _connectionPool = connectionPool;
}
```

The connection pool should probably be registered as a singleton, so it's shared across requests.

Hope this helps. If you can tell me which DI container you're using (Microsoft's ServiceProvider, Autofac, or SimpleInjector), and a bit more about what you're trying to achieve, I can probably go into more detail.

**Comment by tahasi** [comment]
Hello @soxtoby that's terrific. That's consistent with the other ASP.NET DI handling; making my life and future maintainers so much easier.

Thank you so much for this terrific library. I've been very happy with how everything just works.
