### ISSUE TITLE
SlackNet and SlackNet.AspNetCore referencing vulnerable packages

### ISSUE THREAD

**Issue by Skintkingle** [soxtoby/SlackNet#209]
SlackNet 0.13.2 and SlackNet.AspNetCore 0.13.2 are both referencing vulnerable package versions of the following packages:

System.Net.Http 4.3.0
System.Net.Security 4.3.0
System.Text.Encodings.Web 4.5.0
System.Text.RegularExpressions 4.3.0

Hopefully these are just bumps in versions to get off the vulnerable versions. :)

**Comment by soxtoby** [comment]
Thanks for raising this, @Skintkingle. All of these are transitive dependencies, so it might take some time to figure out the best way to update these. In the meantime, you can avoid the vulnerable package versions by referencing the packages directly in your own project.

**Comment by soxtoby** [comment]
Should be resolved in [v0.13.3](https://github.com/soxtoby/SlackNet/releases/tag/v0.13.3).

**Comment by Skintkingle** [comment]
Perfect, thank you so much!

**Comment by NinosMan** [comment]
This seems to have happened again on `System.Private.Uri`

**Comment by soxtoby** [comment]
@NinosMan as far as I can tell, `System.Private.Uri` is not a dependency of any of the SlackNet projects, so it's probably coming from one of your other dependencies. You can run [dotnet nuget why](https://learn.microsoft.com/en-us/dotnet/core/tools/dotnet-nuget-why) to find out what package is bringing it in.
