### ISSUE TITLE
ReactionItem missing channel and ts

### ISSUE THREAD

**Issue by JacobTheisen** [soxtoby/SlackNet#211]
ReactionItem in ReactionAdded and ReactionRemoved are missing channel and ts parameters described in https://api.slack.com/events/reaction_added. This makes it impossible(?) to get the item the reaction was reacted to from within the reactionhandler.

current reactionItem:
```
public class ReactionItem
  {
    public string Type { get; set; }
  }
```

**Comment by soxtoby** [comment]
Thanks for raising this, @JacobTheisen. I'll add the missing properties.

**Comment by soxtoby** [comment]
Ah, actually I take that back - there are three types of `ReactionItem`s that all have different properties: `ReactionFile`, `ReactionFileComment`, and `ReactionMessage`. You'll need to check if your `ReactionItem` is a `ReactionMessage`, and then access then `Channel` and `Ts` from there.
