### ISSUE TITLE
Replace nullable CancellationToken? parameters

### ISSUE THREAD

**Issue by ea-jc** [soxtoby/SlackNet#213]
Thanks for the library!

A minor ticket here - I notice that most of the async APIs have optional nullable CancellationTokens e.g. `.Send(...., CancellationToken? ct = null)`

Typically, as demonstrated by the .NET Core libraries, these should be declared as `CancellationToken ct = default` to avoid needless null handling.

The nullable parameters cause some unexpected issues with mocking, for example in Moq, if I use `It.IsAny<CancellationToken>()` which is accepted, it does not work if I don't pass a `CancellationToken.None` at the callsites.  I know I could use `It.IsAny<CancellationToken?>()` but given the universal conventions in other libs/core, I think this is a worthwhile change to bring SlackNet into line.

**Comment by soxtoby** [comment]
Thanks for pointing this out, @ea-jc. Honestly hadn't occurred to me that the default `CancellationToken` would be equivalent to `None`, but it makes perfect sense in retrospect. This will definitely be better than nullables everywhere, so I'll change everything over.

**Comment by soxtoby** [comment]
Available now in [v0.15.0](https://github.com/soxtoby/SlackNet/releases/tag/v0.15.0).

**Comment by ea-jc** [comment]
Thanks for the prompt turn around
