### ISSUE TITLE
ToDateTime throws away precision

### ISSUE THREAD

**Issue by anielsen** [soxtoby/SlackNet#214]
Hi!

It looks like the timestamps from slacks gets converted to a decimal number before converting to a DateTime. Because the timestamps uses microseconds this looses prevision. This happens in Utils.ToDateTime.

It would be nice to have full precision so that MessageEvent.Ts and MessageEvent.Timestamp represents the same value.

**Comment by soxtoby** [comment]
The `ToDateTime()` helper now includes microseconds, although it's worth noting that message `Ts` properties are _not_ necessarily accurate down to the microsecond.

From the [docs](https://api.slack.com/messaging/retrieving#individual_messages):
> They _look_ like UNIX/epoch timestamps, hence `ts`, with specified milliseconds. But they're actually message IDs, even if they're partially composed in seconds-since-the-epoch.

Including the extra precision in the `DateTime`s should be useful for sorting messages, but I would recommend against using `DateTime`s to identify a message - stick to the `Ts` string.

**Comment by soxtoby** [comment]
This change is now available in [v0.15.1](https://github.com/soxtoby/SlackNet/releases/tag/v0.15.1).
