### ISSUE TITLE
SlackNet.Bot namespace unvailable

### ISSUE THREAD

**Issue by bjorndavis** [soxtoby/SlackNet#3]
The following are the only namespaces available to include after installing the NuGet package:

```
using SlackNet;
using SlackNet.Rtm;
using SlackNet.Events;
using SlackNet.Interaction;
using SlackNet.WebApi;
```

How do I add a reference to `SlackNet.Bot`?  I'm assuming that's what I need to use the sample code listed:

```
var bot = new SlackBot("<your bot token here>");
await bot.Connect();
```

**Comment by soxtoby** [comment]
Good question. `SlackBot` and the `SlackNet.Bot` namespace are in the SlackNet.Bot NuGet package, not the SlackNet package. I'll update the readme to make this clearer.

**Comment by bjorndavis** [comment]
Ah - thanks!
