### ISSUE TITLE
Thanks Simon

### ISSUE THREAD

**Issue by mblack-montag** [soxtoby/SlackNet#34]
This post isn't an issue.  Just wanted to say thanks for updating this project.  Oh and thanks for the Azure Functions love.  :D  I finished my data and domain layers and just started working on my Slack functionality.  Now I don't!

I'd like to contribute if I can.  I've started to update some of the events and objects as Slack has been busy making changes.  Unfortunately, their Open API spec is pretty out of date.  Even their own Slack Api website is incomplete vs what you see when using their api.  I noticed updating my Slack app that their scopes feature now renders the RTM Api obsolete.

Anyway, I had forked the project and I can check in the objects I've updated.  I don't know if you want anything I've done or if you have a way of updating them.  I've always used TFS for version control and I'm still learning Git.  Let me know how I can help.

Kind regards,
Mike

**Comment by soxtoby** [comment]
Thanks for the feedback 🤗. If you push up your changes to your fork, I can take a look and pull in changes as appropriate.

Slack's documentation is very good, but often leaves important or useful details out, so if there's any extra information they're sending that I've missed, then I'm more than happy to add it in.

**Comment by kinetiq** [comment]
Checked out the azure function-related code trying to find some patterns for working with slash commands. Could you consider writing some documentation to show how this is supposed to work? 

I found this:

`        [FunctionName("options")]
        public async Task<IActionResult> Command([HttpTrigger(AuthorizationLevel.Anonymous, "post")] HttpRequest request)        {
        return SlackResponse(await _requestHandler.HandleSlashCommandRequest(request, _endpointConfig).ConfigureAwait(false));

}

`

...But I'm having a hard time following all that abstraction. I'm guessing PingHandler eventually runs and that's wired up in Startup, but I don't feel like I can step in and use this without some comments of some kind. :)

**Comment by soxtoby** [comment]
@kinetiq the `SlackEndpoints` class in the AzureFunctionExample project is essentially a replacement for the middleware that gets hooked up for you in ASP.NET, and provides generic handlers for Slack requests. All setup for specific request handlers should happen inside `.AddSlackNet()` in the `Startup` class. The EventsExample project has more examples of this kind of configuration.

I hope this helps. I've only just started playing with Azure Functions myself, so I'm not sure if this is the simplest way to set things up. I'll at least try to add some more documentation around it in the next week or two.
