### ISSUE TITLE
Slack returned an error response: not_allowed_token_type

### ISSUE THREAD

**Issue by russov** [soxtoby/SlackNet#35]
Hello. I try to use the lib to create a bot for slack but I get the error:
My code:
```
private const string BotToken = "xoxb-....";
var bot = new SlackBot(BotToken);
await bot.Connect();
```
But I have got the next error (Slack returned an error response: not_allowed_token_type):
![image](https://user-images.githubusercontent.com/5598641/76770746-70f0fa00-67af-11ea-881d-3616292f0ce7.png)

Why do I get the error? Is it normal?

**Comment by mblack-montag** [comment]
It looks like the SlackNet Bot code uses the RTM Api.  Slack has introduced scoped apps or "granular permission" apps.  All new apps will use this new scopes feature.  These new apps won't work with RTM Api only the Events API.  You can still create an app which works with the RTM Api by clicking "Create a Classic Slack APP" on this page:  https://api.slack.com/rtm.

**Comment by russov** [comment]
Thanks a lot. It helps me. Good luck.
