### ISSUE TITLE
ExternalMultiSelectValue doesn't inherit ElementValue

### ISSUE THREAD

**Issue by mblack-montag** [soxtoby/SlackNet#41]
I'm using this line of code:

`viewSubmission.View.State.GetValue<ExternalMultiSelectValue>(InputSecuritiesMultiSelectBlockId, SecuritiesSelector.ActionId).Value`

but I'm getting a "no implicit reference conversion" warning in Visual Studio.  When I checked SlackNet.Blocks.ExternalMultiSelectMenu class file, the ExternalMultiSelectValue class isn't inheriting from ElementValue.  Shouldn't it be?

**Comment by soxtoby** [comment]
Fixed in latest release - thanks @mblack-montag.
