### ISSUE TITLE
Help setting up events

### ISSUE THREAD

**Issue by pkmetski** [soxtoby/SlackNet#50]
Hi,
I am trying to migrate away from my custom Slack integration to SlackNet. One of the use cases I have is reacting to a button press in an action block element. My current implementation has a Web API controller endpoint where the Slack interactivity is configured. On this endpoint I receive the payload of the interaction. I'd like to stramline this by utilizing the SlackNet events, but can't figure out how/where this interaction endpoint comes into play.
I have tried running the SlackNet.EventsExample without success - opening the IIS express page results in a 404. Can someone point me in the right direction, please?

**Comment by soxtoby** [comment]
Hi @pkmetski,

The SlackNet.EventsExample is purely an API project, so there's no page to open - it just responds to Slack requests. It also needs to be hooked up to your own Slack app, which I really need to get around to documenting 😬.

The key part to look at though is `Startup.cs`. This is where event handlers are registered with SlackNet, and where the SlackNet endpoints are configured. These endpoints will take the place of your controller action, and handle the boring details of interacting with Slack for you.  By default, the path to the interactivity request handler is `/slack/action`.

Specifically for your scenario, you'll want something similar to the `.RegisterBlockActionHandler<ButtonAction, BlockCounter>(BlockCounter.Add1)` line, but replace  `BlockCounter` with your own handler class, and `BlockCounter.Add` with the callback ID you've used for the button.

Hope this helps.

**Comment by pkmetski** [comment]
Hi @soxtoby. Thanks for the help, this solved it! Great work with the library, it saved me a lot of code and is a treat to work with :)

I have created a PR with the above readme update [here](https://github.com/soxtoby/SlackNet/pull/51)

**Comment by ciubiu** [comment]
> It also needs to be hooked up to your own Slack app, which I really need to get around to documenting

I also have problem to hook up SlackNet.EventsExample with my Slack. Then I try to update the slack/events address then I get messages that folder slack/events not found and therefore URL didn't respond with the value of the challenge parameter. I got it all working in python API, but I would like to learn C# more.

**Comment by soxtoby** [comment]
Hi @ciubiu, have you made your website externally accessible? Slack needs to be able to access your application over the internet.

**Comment by ciubiu** [comment]
I am new to web development. I use ngrok for port forwarding and it is working for my bot made with Python Bolt Slack API. When running EventsExample and changing Slack event url to enter current ngrok address, the POST /slack/events is received by Ngrok ("type": "url_verification") and ngrok web interface says 404 Not Found (C o n t e n t - L e n g t h :   0).
Console says Application started. Press ... , and doesn't show any errors even then I get POST messages via Ngrok.
Maybe there is better way to check if connection okey?

**Comment by soxtoby** [comment]
Should be `/slack/event`, not `/slack/events`. 

If that's not it, I would try hitting the endpoint manually - SlackNet will reject the request (unless you've correctly mimicked a real Slack request), but it shouldn't be a 404. If you're running the example from source, you can also put a breakpoint in `SlackRequestMiddleware` adlnd verify that SlackNet is haning the request.
