### ISSUE TITLE
Azure Functions v3 IActionResult issue with v 0.70 +

### ISSUE THREAD

**Issue by mblack-montag** [soxtoby/SlackNet#53]
Hi Simon,

Thanks for the new version, especially global shortcuts.

This issue isn't a bug with SlackNet as much as it is a compatibility issue with Azure Functions v2 and v3 (I think).

I've been using Azure Functions v3 and v 0.6.6 for SlackNet and SlackNet.AspNetCore.  I wanted to use the new global shortcuts feature for a new Slack project for which I'm using v 0.7.1.  During some quick testing I ran into an issue with the Actions function.  The handlers work fine but Slack acts like it's not receiving an acknowledgement response whether you're using a global shortcut handler or a block action handler for a button.  I think I traced it down to the return type change from SlackResponse to SlackResult, ContentResult to IActionResult respectively.  It appears that with Azure Functions v2 and v3 there are issues with returning an ActionResult from a function that are not consistent with ASP.Net controller.  With Azure Functions v2 there is an application setting which fixes the issue while with v3 there is not yet a similar setting.  The links to the issues on github are below.

https://github.com/Azure/azure-functions-host/issues/4396 
https://github.com/Azure/azure-functions-host/issues/4907 

Azure Application Insights doesn't seem to like it either as the Invocation Tracing for that function isn't showing any activity even though the application logs do.  I can see the return type is EmptyResult with a status code of 200.  I can also see Slack retrying the call twice more but those return status code 500 as should be expected.

I did a quick test and changed my Actions function to return new OkResult instead of SlackResult and both Slack and Application Insights showed normal behavior.

Here is my project config:

```csharp

  <PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>
    <AzureFunctionsVersion>v3</AzureFunctionsVersion>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Azure.Functions.Extensions" Version="1.0.0" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="3.1.4" />
    <PackageReference Include="Microsoft.NET.Sdk.Functions" Version="3.0.7" />
    <PackageReference Include="SlackNet" Version="0.7.1" />
    <PackageReference Include="SlackNet.AspNetCore" Version="0.7.1" />
  </ItemGroup>

```

**Comment by soxtoby** [comment]
Thanks for raising this - I'll give it a go and see if I can tweak or adapt the return type to work with v3 functions.

**Comment by mblack-montag** [comment]
Looks like the 0.72 release resolved this issue.  Thanks Simon.

**Comment by soxtoby** [comment]
There weren't any changes in v0.7.2 that I would have expected to fix this 😕 so please let me know if you hit this again.

**Comment by mblack-montag** [comment]
I did add a flag to the Azure function app configuration but I didn’t think it worked for v3 yet.  I’ll try to test it by removing it.
