### ISSUE TITLE
Slack API Deprecation for Groups\Channels\Im\mpim in favor for conversations.*

### ISSUE THREAD

**Issue by sergey-litvinov** [soxtoby/SlackNet#55]
Hey Simon,

Firstly just wanted to say thanks for the great work. i'm working on slack bot and liked your implementation and thanks for that.

I got one problem related to https://api.slack.com/changelog/2020-01-deprecating-antecedents-to-the-conversations-api . I'm using Classic Slack App and RTM Api for the bot. And when any message comes, SlackBot.cs will call `CreateSlackMessage` that will call `GetHubById` that will do
https://github.com/soxtoby/SlackNet/blob/ae1a2f2cd6f1c24998349c5910ccc144e8c26e08/SlackNet.Bot/SlackBot.cs#L286-L290

For me for channel messages it fails as `_api.Channels.Info` returns 
```
{
    "ok": false,
    "error": "method_deprecated",
    "response_metadata": {
        "messages": [
            "[ERROR] This method is retired and can no longer be used. Please use conversations.info instead. Learn more: https://api.slack.com/changelog/2020-01-deprecating-antecedents-to-the-conversations-api."
        ]
    }
}
```

It happens as my app was created after June 10th, 2020, so all channels.*,groups.*,im.*, mpim.* are returning this result. Existing apps would work up to February 24th, 2021 and after that would get the same error.

I can try to make some PR with the change to migrate channels\groups\im\mpim usage in the bot to `conversations.*` endpoints but want to understand your intention about that and how you would like to handle that. Like do you have any specific plans on how code should be implemented for that? or maybe you want to have it under some feature flag\etc as it will affect existing clients as well. I guess conversation.* responses should have the same data as old endpoints but still

**Comment by soxtoby** [comment]
Thanks for raising this - I thought I had until February to update the code, but I guess not 😱.

I really want to avoid breaking people's existing code, so I'm going to have to think about how this should be done. I should be able to get a fix in in the next few days though, even if it's just something behind a feature flag like you suggested.

**Comment by sergey-litvinov** [comment]
Thank you very much!

**Comment by hughesmk** [comment]
+1 I tripped on the same issue.   Thanks Sergey for the spot on analysis.

**Comment by soxtoby** [comment]
Added conversations-based methods to SlackBot in v0.7.3. Additionally, all the existing methods go through the conversations API, so they should continue to work.

**Comment by sergey-litvinov** [comment]
Thanks!
