### ISSUE TITLE
FetchConversations goes on endless loop

### ISSUE THREAD

**Issue by spairous** [soxtoby/SlackNet#60]
I tried using the latest version (0.7.7) and noticed that I'm not getting any response when executing SlackBot.GetConversationsByName(name). 

Looking a bit in the code I noticed that in FetchConversations you have a:
`} while (cursor != null);` 

but looking at the response using the Slack test:
https://api.slack.com/methods/conversations.list/test

I noticed that the **next_cursor** is an emptu string not null! 
`"response_metadata": { "next_cursor": "" }`

Could you please have a look and let me know?

**Comment by soxtoby** [comment]
Yep you're exactly right. What's worse, I was already handling empty strings in other paging code and missed it 🤦. Should be fixed now in v0.7.8.
