### ISSUE TITLE
Cen't send message as Bot

### ISSUE THREAD

**Issue by m4rcelpl** [soxtoby/SlackNet#63]
Hi!

When i try send message like this:

```csharp
 var SendMessage = await api.Chat.PostMessage(new SlackNet.WebApi.Message {Channel = "ChannelName", Text = "Hello", Username = "MyBot", AsUser = false});
```
i got error: "Slack returned an error response: invalid_arguments."

And example from readme also won't work :)

```csharp
var channels = await api.Channels.List();
```
"Slack returned an error response: method_deprecated."

**Comment by soxtoby** [comment]
Hi @m4rcelpl,

The `AsUser` property will only work with "classic" Slack apps. With new Slack apps, I believe you'll want to use the bot user token to connect to Slack and leave `AsUser` as the default of `null`. See the [authorship section of chat.postMessage](https://api.slack.com/methods/chat.postMessage#authorship) for more details.

The `Channels` API has indeed been deprecated by Slack and replaced with the `Conversations` API.

I'll update the readme and maybe mark the deprecated APIs as `Obsolete` while I'm at it.

Hope this helps.

**Comment by soxtoby** [comment]
I've updated the readme and marked the deprecated APIs as `Obsolete`. I'll remove them completely in February once Slack shuts them off.
