### ISSUE TITLE
Send with markdown

### ISSUE THREAD

**Issue by BadgerTheAdger** [soxtoby/SlackNet#64]
Hi guys how do I send a message with markdown?

**Comment by soxtoby** [comment]
Slack's API is a bit non-obvious in this case: you'll need to add a `SectionBlock` to a `Message`'s `Blocks` list, and use a `Markdown` object for its `Text` property. Something like this:
```c#
_slackApi.Chat.PostMessage(new Message
   {
       Channel = "#general",
       Blocks = { new SectionBlock { Text = new Markdown("Make something *bold*") } }
   });
```

Hope that helps.

**Comment by BadgerTheAdger** [comment]
Actually you can do it pretty easily via their api... just post  { text =
"myTextWithMarkdown", chat = "mychat" } and in the header bearer token at
the postMessage resource... Idk why one even needs this library as its
simply not working
