### ISSUE TITLE
Ephemeral Response support?

### ISSUE THREAD

**Issue by wonnyz** [soxtoby/SlackNet#74]
Hello, I want to reply an ephemeral message to sender when the bot received an incorrect command from user.
But only to find that SlackBot doesn't support ephemeral messaging, and there is no way to send without using a SlackApiClient.

and I found that you implemented ephemeral messaging on #21, but that PR is discarded! 

Can we have a ephemeral reply support with SlackBot?

**Comment by soxtoby** [comment]
Thanks for raising this, @wonnyz. I'll merge that change in soon.

**Comment by soxtoby** [comment]
Now available in v0.7.12

**Comment by wonnyz** [comment]
works like charm. Thank you very much!
