### ISSUE TITLE
Missing Description in SlackNet.Blocks.Option

### ISSUE THREAD

**Issue by s0nyguy** [soxtoby/SlackNet#80]
Hey Simon,

Looks like the SlackNet.Blocks.Option model is missing the Description field as per Slack documentation

https://api.slack.com/reference/block-kit/composition-objects#text

I just added it to the model and it started working perfectly, no further changes required

    public TextObject Description { get; set; }

Thanks!

**Comment by soxtoby** [comment]
Hi @s0nyguy, thanks for raising this. I've pushed up v0.8.2 with the fix.
