### ISSUE TITLE
Proxy with Socketmode dependency injection

### ISSUE THREAD

**Issue by hughesmk** [soxtoby/SlackNet#84]
I am trying to figure out how to use autofac (or any dependency injection) to configure a proxy for use with socketmode.   Obviously my first issue is the conversion from httpclient to Func<HttpClient>.   Are there any working examples of using a proxy/custom httpclient with socketmode and dependency injection?

**Comment by soxtoby** [comment]
Hi @hughesmk,

The `Func<HttpClient>` is a way for the `Http` service to get a `HttpClient` per request, but it's up to the user how to provide the client. If you've registered your `HttpClient` with the container, you can override the `Http` service with:

```c#
containerBuilder.AddSlackNet(s => s.UseHttp(c => Default.Http(c.Resolve<SlackJsonSettings>(), () => c.Resolve<HttpClient>())));
```

This will resolve the `HttpClient` from the container each request, relying on the container to handle how & when the client is created.

If you only have a single instance of the `HttpClient` and you have access to it in the configuration code, you can change the `Func` to just return the instance directly if you want.

I'm guessing you'll need to override the `WebSocketFactory` as well - this one's a bit simpler:

```c#
containerBuilder.AddSlackNet(s => s.UseWebSocketFactory<MyWebSocketFactory>());
```

Hope this helps.

**Comment by hughesmk** [comment]
I am clearly missing something here.  Intermittently this works, but it is inconsistent.   From logs in my overriden websocketfactory I can see that when it does not work the websocketfactor never gets invoked.  If I resolve httpclient and websocketfactory after the build is called I can see that they are the proper ones and have the proxy configured


                 var containerBuilder = new ContainerBuilder();

                HttpClientHandler handler = getProxy();
                handler.ServerCertificateCustomValidationCallback += ValidateServerCertificate;

                containerBuilder.Register(c => new HttpClient(handler) {}).As<HttpClient>().SingleInstance();
                
                //add http here as it explodes when added below or added after the bot connection is created
                containerBuilder.AddSlackNet(s => s.UseHttp(c => Default.Http(c.Resolve<SlackJsonSettings>(), () => c.Resolve<HttpClient>())));

                //setup the bot connection
                containerBuilder.AddSlackNet(s =>
                    s.UseWebSocketFactory<SlackNetx.WebSocketFactory>()
                    .UseApiToken(_config.GetString("slacktoken"))
                    .UseAppLevelToken(_config.GetString("apptoken"))
                    .RegisterEventHandler(ctx => new SlackBotEventHandler(_logger, _config, this))
                    );
                
                SlackContainer = containerBuilder.Build();

                //get our client
                var client = SlackContainer.Resolve<ISlackSocketModeClient>();

                //make our connection
                _logger.Log(LogLevel.WARNING, "Before Connect");
                await client.Connect();
                _logger.Log(LogLevel.WARNING, "After Connect");

**Comment by soxtoby** [comment]
Try putting all the SlackNet configuration in a single `AddSlackNet` call. I'm pretty sure the second call will override the configuration in the first call.

**Comment by hughesmk** [comment]
Thanks had tried that and was getting errors.  Based on your direction though I went ahead and pursued that direction, here is what I ended up with that at least in initial testing is working consistently


```
containerBuilder.AddSlackNet(s =>
                    s .UseHttp(c =>
                    {
                        //pre-resolve the client or we get an object disposed error
                        var h = c.Resolve<HttpClient>();
                        return Default.Http(c.Resolve<SlackJsonSettings>(), ()=>h);
                    })
                    .UseWebSocketFactory<SlackNetx.VzWebSocketFactory>()
                    .UseApiToken(slacktoken))
                    .UseAppLevelToken(_config.GetString(apptoken))
                    .RegisterEventHandler(ctx => new SlackBotEventHandler(_logger, _config, this))
                    );
```

**Comment by soxtoby** [comment]
Hmm... would make sense that the `IComponentContext` is disposed after resolving `IHttp`. I think `c.Resolve<Func<HttpClient>>()` should work for the second argument of `Default.Http`, although what you've got should be fine too, since your `HttpClient` is a singleton.
