### ISSUE TITLE
Send Files

### ISSUE THREAD

**Issue by Paffo** [soxtoby/SlackNet#88]
Hello,
I checked the source but i could see no implementation for sending files as attachments to messages.
Is it possible?
I have a Bot that on request, must create and send a simple excel file,
how would i have to proceed in order to implement this?

Thanks

**Comment by mblack-montag** [comment]
Hi Paffo,

Check out these Slack API pages:
https://api.slack.com/methods/files.upload
https://api.slack.com/messaging/files/uploading

Using SlackNet you can do something like this:
`_slack.Files.Upload(CreateExcelFile(), "xlsx", "Text.xlsx", "Test Title", channels: new List<string> {"5"})`

Creating Excel files in C# is outside the scope of this framework.  That said I have used the ClosedXML nuget package to create simple Excel files.  Here is a quick sample.  I would obviously not write this for production but it gives you an idea.

```
private static byte[] CreateExcelFile()
{
    using var workbook = new XLWorkbook();
    var worksheet = workbook.Worksheets.Add("Data");
    worksheet.Cell(1, 1).Value = "xyz";
    worksheet.Cell(2, 1).Value = "test";
    using var stream = new MemoryStream();
    workbook.SaveAs(stream);

    return stream.ToArray();
}
```

**Comment by Paffo** [comment]
Hi,
thanks for your reply, i have the excel file already generated and conveniently enough the output is a byte[] so no problem.
But unfortunately i cannot get your code to work, i'm using a SlackBot instance, not a SlackApiClient directly so i do not have direct access to the Files.Upload method.
Should i switch everything to SlackNet mainly instead of using SlackBot or there's a way to get the ApiClient methods from the Bot instance? (i can see it can be initialized with one, is it a private property of it?)

**Comment by soxtoby** [comment]
Hi @Paffo,

You'll need to use the SlackApiClient to upload files, but there's no need to switch everything over. SlackBot uses an API client internally for sending messages and fetching users & conversations, but there's nothing wrong with having multiple client instances using the same bot token.

SlackBot makes it easy to listen for and respond to user messages, while SlackApiClient gives you full access to the API, but no good way to listen for messages, so mixing and matching them depending on what you need to do is definitely the way to go.

Hope that helps.

**Comment by ClubSpeedJustinG** [comment]
If anyone else is struggling with sending files, then [this](https://medium.com/@justinshawngerber/send-a-file-to-a-slack-channel-using-c-3d036248c675) article can help.

**Comment by casals** [comment]
My 2 cents: despite Slack's [official documentation at the moment](https://api.slack.com/methods/files.upload), *all parameters except for `thread_ts` are mandatory*. If you send an upload request with an empty string in any other parameter - even `Title` or `Comment` - you'll get a 400 response (Bad Request).
