### ISSUE TITLE
No team field in the conversations api

### ISSUE THREAD

**Issue by competeya** [soxtoby/SlackNet#89]
_slackClient.Conversations.History(
does  not return the sending users team as exists in the API

**Comment by soxtoby** [comment]
Hi @competeya, thanks for raising this. Are you able to provide a sample JSON response? The Slack documentation for [conversations.history](https://api.slack.com/methods/conversations.history) doesn't include any team information, but if I can see what the JSON looks like it'll be easy for me to add it.

**Comment by competeya** [comment]
See attached sample of a conversation history message:

 {
            "client_msg_id": "1e63ffb1-e7a6-4354-82c3-f0ecc38f794c",
            "type": "message",
            "text": "<https://stanfordmlgroup.github.io/competitions/chexpert/>",
            "user": "UBYJVLHUL",
            "ts": "1548420502.005100",
            "team": "TBY4HLD08",
            "attachments": [
                {
                    "title": "CheXpert: A Large Dataset of Chest X-Rays and Competition for Automated Chest X-Ray Interpretation.",
                    "title_link": "https://stanfordmlgroup.github.io/competitions/chexpert/",
                    "text": "CheXpert is a large dataset of chest x-rays and competition for automated chest x-ray interpretation, which features uncertainty labels and radiologist-labeled reference standard evaluation sets.",
                    "fallback": "CheXpert: A Large Dataset of Chest X-Rays and Competition for Automated Chest X-Ray Interpretation.",
                    "image_url": "https://stanfordmlgroup.github.io/competitions/chexpert/img/logo.jpg",
                    "from_url": "https://stanfordmlgroup.github.io/competitions/chexpert/",
                    "image_width": 469,
                    "image_height": 250,
                    "image_bytes": 58261,
                    "service_icon": "https://stanfordmlgroup.github.io/favicon.ico",
                    "service_name": "stanfordmlgroup.github.io",
                    "id": 1,
                    "original_url": "https://stanfordmlgroup.github.io/competitions/chexpert/"
                }
            ]
        },

**Comment by soxtoby** [comment]
Perfect. I'll have a fix up soon.

**Comment by competeya** [comment]
Checked it and works well, thx.
