### ISSUE TITLE
Modal support

### ISSUE THREAD

**Issue by wolfpackt99** [soxtoby/SlackNet#99]
Will modal support be added? seems it slightly different than Dialog

**Comment by soxtoby** [comment]
Hi @wolfpackt99, you can open a modal with `ViewsApi.Open`. You can see an example usage in [SlackNet.EventsExample/AppHome.cs](https://github.com/soxtoby/SlackNet/blob/master/SlackNet.EventsExample/AppHome.cs#L52). Note that modals must be opened in response to a user interaction, and you'll need to pass along the `TriggerId` from that action.

Hope that helps.
